project:
  type: website
  output-dir: docs

website:
  title: "Zhiyuan - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
          - text: Week 1
          - href: weekly-notes/week-01-notes.qmd
          - text: Week 2
      - text: Labs
        menu:
          - text: Lab 0
          - href: Labs/Lab0/lab0_template.qmd
          - text: Lab 1
          - href: Labs/Lab1/assignment1_template.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
