{
  "hash": "9b8e1033e39962d089afc1309c92cd28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Philadelphia Eviction Prediction Model\"\nsubtitle: \"MUSA 5080 - Final Project\"\nauthor: \"Zhiyuan Zhao & Fan Yang\"\ndate: \"December 3, 2025\"\nformat: \n  html:\n    code-fold: true\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n# 1. Abstract\n\nEviction is a major housing crisis in Philadelphia. When families are evicted, they often end up homeless, children have to switch schools, and it becomes much harder to find new housing. Can we predict which neighborhoods will have the most evictions next month? If we can, the Philadelphia Housing Authority can send resources (legal aid, rental assistance, counseling) to those areas before the evictions happen.\n\nThis analysis builds a prediction model using data from 2020-2025, combining three data sources: weekly eviction filing records for 408 Census tracts, neighborhood characteristics from the Census (poverty rate, renter percentage, etc.), and 311 housing complaint calls. The analysis reveals that evictions are highly predictable - if a neighborhood had many evictions last month, it will likely have many next month too. Clear spatial patterns emerge: eviction \"hotspots\" cluster in North and West Philadelphia, particularly in majority-Black neighborhoods.\n\nThe best model (Enhanced Poisson) achieves a McFadden's R² around 0.22, which is considered \"good\" for count data modeling. The model correctly identifies high-risk areas with approximately 75% accuracy. All 408 Census tracts are classified into risk categories (Very High, High, Moderate, Low, Very Low) to create an \"early warning system\" map that the Housing Authority can use for targeted intervention.\n\nKey limitations: the model works best for short-term predictions (1-2 months ahead) and cannot account for sudden policy changes (like new eviction moratoriums) or economic shocks. Additionally, the model performs slightly worse in majority-Black neighborhoods, which is an equity concern discussed in detail.\n\n------------------------------------------------------------------------\n\n# 2. Setup\n\nThis section initializes the R environment by loading all required packages for spatial analysis, statistical modeling, and data visualization. The packages are organized by their primary function: tidyverse for data manipulation, sf and spdep for spatial analysis, tidycensus for Census data access, and various modeling packages.\n\n\n\n\n\n------------------------------------------------------------------------\n\n# 3. Data Sources\n\nThis analysis integrates three complementary data sources to build a comprehensive picture of eviction risk in Philadelphia. Each source captures a different dimension of housing instability: the Eviction Lab provides direct counts of court filings, the American Community Survey describes neighborhood socioeconomic characteristics, and 311 data captures resident-reported housing problems that may signal emerging instability.\n\n## 3.1 Eviction Data\n\nThe primary dataset comes from the Eviction Lab at Princeton University, which tracks eviction court filings across the United States. For Philadelphia, weekly eviction filing counts are available for each Census tract from 2019 through 2025. This granular temporal resolution allows us to capture both short-term fluctuations (such as end-of-month spikes when rent is due) and longer-term trends (such as the effects of eviction moratoriums).\n\nThese data represent eviction *filings*, not completed evictions. Many filed cases are dismissed, settled, or withdrawn before an actual eviction occurs. However, even a filing can have serious consequences for tenants, including damaged credit scores, difficulty finding future housing, and the stress of legal proceedings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LOAD AND PROCESS EVICTION DATA\n\neviction_weekly <- read_csv(\"data/philadelphia_weekly_2020_2021.csv\") %>%\n  # Remove sealed records that lack geographic information\n  filter(GEOID != \"sealed\") %>%\n  mutate(\n    # Parse date string into proper date format\n    week_date = ymd(week_date),\n    \n    # Extract temporal components for potential seasonality analysis\n    year = year(week_date),\n    month = month(week_date),\n    \n    # Create binary indicator for CDC eviction moratorium period\n    # The moratorium was announced 9/4/2020 and expired 8/26/2021\n    pandemic_moratorium = ifelse(\n      week_date >= \"2020-09-04\" & week_date <= \"2021-08-26\", \n      1, 0\n    )\n  )\n\n# GENERATE SUMMARY STATISTICS\n\neviction_summary <- tibble(\n  Metric = c(\"Total observations\", \"Census tracts\", \"Date range\", \"Number of weeks\"),\n  Value = c(\n    format(nrow(eviction_weekly), big.mark = \",\"),\n    n_distinct(eviction_weekly$GEOID),\n    paste(min(eviction_weekly$week_date), \"to\", max(eviction_weekly$week_date)),\n    n_distinct(eviction_weekly$week)\n  )\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(eviction_summary, caption = \"Eviction Data Summary\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Eviction Data Summary\n\n|Metric             |Value                    |\n|:------------------|:------------------------|\n|Total observations |125,256                  |\n|Census tracts      |408                      |\n|Date range         |2019-12-29 to 2025-11-09 |\n|Number of weeks    |307                      |\n\n\n:::\n:::\n\n\nThe eviction data structure provides a panel dataset where each observation represents one Census tract in one week. \n\n------------------------------------------------------------------------\n\n## 3.2 Census/ACS Data\n\nThe American Community Survey (ACS) provides socioeconomic indicators at the Census tract level. We use the 2021 5-year estimates, which aggregate survey responses from 2017-2021 to provide reliable estimates even for small geographic areas. The 5-year estimates trade temporal precision for statistical reliability - a tradeoff that makes sense for our application since neighborhood demographics change slowly.\n\nThe variables selected capture multiple dimensions of eviction risk identified in the housing literature: housing tenure (renter vs. owner), rent burden (how much income goes to rent), economic stress (poverty, unemployment), educational attainment, and housing stock age (older buildings may have more maintenance issues). Each variable was chosen based on either theoretical relevance or empirical associations found in prior eviction research.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# DEFINE ACS VARIABLES OF INTEREST\n# Variable codes follow Census Bureau naming conventions:\n# B-series = detailed tables, prefix indicates table number\n\nacs_vars <- c(\n  # Population counts\n  total_pop = \"B01003_001\",           # Total population\n  \n  # Housing unit counts and occupancy status\n  total_units = \"B25001_001\",         # Total housing units\n  occupied_units = \"B25002_002\",      # Occupied housing units\n  vacant_units = \"B25002_003\",        # Vacant housing units\n  owner_occupied = \"B25003_002\",      # Owner-occupied units\n  renter_occupied = \"B25003_003\",     # Renter-occupied units\n  \n  # Rent metrics\n  median_rent = \"B25064_001\",         # Median gross rent (dollars)\n  \n  # Rent burden indicators (% of income spent on rent)\n  rent_burden_total = \"B25070_001\",   # Total renters (denominator)\n  rent_burden_30_35 = \"B25070_007\",   # Renters paying 30-34.9% of income\n  rent_burden_35_40 = \"B25070_008\",   # Renters paying 35-39.9% of income\n  rent_burden_40_50 = \"B25070_009\",   # Renters paying 40-49.9% of income\n  rent_burden_50plus = \"B25070_010\",  # Renters paying 50%+ of income (severely burdened)\n  \n  # Income and economic indicators\n  median_income = \"B19013_001\",       # Median household income\n  poverty_total = \"B17001_001\",       # Total population for poverty status\n  poverty_below = \"B17001_002\",       # Population below poverty line\n  labor_force = \"B23025_003\",         # Civilian labor force\n  unemployed = \"B23025_005\",          # Unemployed civilians\n  \n  # Educational attainment (age 25+)\n  edu_total = \"B15003_001\",           # Total population 25 years and over\n  edu_bachelors = \"B15003_022\",       # Bachelor's degree\n  edu_masters = \"B15003_023\",         # Master's degree\n  edu_professional = \"B15003_024\",    # Professional school degree\n  edu_doctorate = \"B15003_025\",       # Doctorate degree\n  \n  # Housing age\n  built_total = \"B25034_001\",         # Total housing units (year built)\n  built_before_1940 = \"B25034_011\"    # Built 1939 or earlier\n)\n\n# FETCH ACS DATA WITH GEOMETRY\n\nphilly_acs <- get_acs(\n  geography = \"tract\",\n  variables = acs_vars,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2021,\n  geometry = TRUE,              # Include spatial boundaries\n  output = \"wide\",              # One column per variable\n  progress = FALSE              # Suppress progress bar\n)\n\n# CALCULATE DERIVED VARIABLES\n# Transform raw counts into interpretable percentages and ratios\n\nphilly_acs <- philly_acs %>%\n  mutate(\n    # Percentage of occupied units that are renter-occupied\n    pct_renter = ifelse(occupied_unitsE > 0, \n                        renter_occupiedE / occupied_unitsE * 100, NA),\n    \n    # Vacancy rate as percentage of total units\n    vacancy_rate = ifelse(total_unitsE > 0, \n                          vacant_unitsE / total_unitsE * 100, NA),\n    \n    # Calculate total rent-burdened renters (paying >30% of income)\n    rent_burdened = rent_burden_30_35E + rent_burden_35_40E + \n                    rent_burden_40_50E + rent_burden_50plusE,\n    \n    # Percentage of renters who are rent-burdened\n    pct_rent_burdened = ifelse(rent_burden_totalE > 0, \n                               rent_burdened / rent_burden_totalE * 100, NA),\n    \n    # Percentage severely rent-burdened (paying >50% of income)\n    pct_severe_burden = ifelse(rent_burden_totalE > 0, \n                               rent_burden_50plusE / rent_burden_totalE * 100, NA),\n    \n    # Poverty rate\n    poverty_rate = ifelse(poverty_totalE > 0, \n                          poverty_belowE / poverty_totalE * 100, NA),\n    \n    # Unemployment rate (among civilian labor force)\n    unemployment_rate = ifelse(labor_forceE > 0, \n                               unemployedE / labor_forceE * 100, NA),\n    \n    # Percentage with college degree or higher\n    college_edu = edu_bachelorsE + edu_mastersE + \n                  edu_professionalE + edu_doctorateE,\n    pct_college = ifelse(edu_totalE > 0, \n                         college_edu / edu_totalE * 100, NA),\n    \n    # Percentage of housing built before 1940\n    pct_old_housing = ifelse(built_totalE > 0, \n                             built_before_1940E / built_totalE * 100, NA)\n  ) %>%\n  # Select only the variables needed for analysis\n  select(\n    GEOID, NAME, geometry,\n    total_pop = total_popE,\n    renter_occupied = renter_occupiedE,\n    median_rent = median_rentE,\n    median_income = median_incomeE,\n    pct_renter, vacancy_rate, pct_rent_burdened, pct_severe_burden,\n    poverty_rate, unemployment_rate, pct_college, pct_old_housing\n  )\n\nn_tracts <- nrow(philly_acs)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## 3.3 311 Complaint Data\n\n311 is Philadelphia's non-emergency service request system. Residents can call 311 to report issues like potholes, abandoned vehicles, or housing code violations. Housing-related 311 complaints may serve as early warning signs of evictions - when tenants report maintenance issues, dangerous conditions, or landlord neglect, it often signals housing instability that could precede displacement.\n\nWe focus specifically on housing-related complaint types that might indicate rental housing distress: maintenance complaints, dangerous building conditions, no heat, infestations, and vacant properties. These complaint types were selected based on their theoretical connection to the landlord-tenant relationship and housing quality issues that often precede evictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# DEFINE FUNCTION TO LOAD 311 DATA BY YEAR\n\nload_311_data <- function(year, data_path = \"data/311\") {\n  # Construct file path for the given year\n  shp_file <- file.path(data_path, paste0(year, \"_public_cases_fc.shp\"))\n  \n  # Return NULL if file doesn't exist (graceful handling)\n  if (!file.exists(shp_file)) return(NULL)\n  \n  # Read shapefile and transform to match ACS coordinate system\n  st_read(shp_file, quiet = TRUE) %>%\n    st_transform(crs = st_crs(philly_acs))\n}\n\n# LOAD ALL AVAILABLE YEARS\n\nyears <- 2020:2025\n\n# Use map() to load each year, handling missing files automatically\ndata_311_list <- map(years, ~load_311_data(.x))\n\n# Combine all years, filtering out NULL entries\ndata_311_all <- bind_rows(data_311_list[!sapply(data_311_list, is.null)])\n\nn_311_total <- nrow(data_311_all)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FILTER TO HOUSING-RELATED COMPLAINT TYPES\n\n# These categories were selected based on their theoretical connection\n# to housing stability and landlord-tenant relationships\n\nhousing_311_types <- c(\n  \"Maintenance Residential or Commercial\",  # General maintenance issues\n  \"Maintenance Complaint\",                  # Specific maintenance complaints\n  \"Building Dangerous\",                     # Structural safety concerns\n  \"Vacant House or Commercial\",             # Abandoned properties (blight indicator)\n  \"No Heat (Residential)\",                  # Essential service failure\n  \"Infestation Residential\",                # Pest problems (habitability issue)\n  \"Fire Residential or Commercial\",         # Fire damage or hazards\n  \"Other Dangerous\",                        # Miscellaneous safety issues\n  \"Dangerous Sidewalk\"                      # Property maintenance obligation\n)\n\nhousing_311 <- data_311_all %>%\n  # Keep only housing-related complaint types\n  filter(service_na %in% housing_311_types) %>%\n  mutate(\n    # Parse request date and calculate week start date\n    request_date = as.Date(requested_),\n    # Align to Sunday-starting weeks to match eviction data\n    week_date = floor_date(request_date, unit = \"week\", week_start = 7)\n  )\n\nn_housing_311 <- nrow(housing_311)\npct_housing <- round(n_housing_311 / n_311_total * 100, 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_311_summary <- tibble(\n  Metric = c(\"Total 311 records\", \"Housing-related complaints\", \"Percentage\"),\n  Value = c(format(n_311_total, big.mark = \",\"), \n            format(n_housing_311, big.mark = \",\"), \n            paste0(pct_housing, \"%\"))\n)\nkable(data_311_summary, caption = \"311 Data Summary\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 311 Data Summary\n\n|Metric                     |Value     |\n|:--------------------------|:---------|\n|Total 311 records          |3,245,433 |\n|Housing-related complaints |218,147   |\n|Percentage                 |6.7%      |\n\n\n:::\n:::\n\n\nHousing-related complaints represent 6.7% of all 311 calls, reflecting the significant role that housing issues play in Philadelphia's urban challenges. These complaints are spatially joined to Census tracts to create weekly complaint counts that can be used as a leading indicator of neighborhood distress.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SPATIAL JOIN: ASSIGN 311 CALLS TO CENSUS TRACTS\n\nhousing_311_tract <- st_join(housing_311, philly_acs %>% select(GEOID))\n\n# AGGREGATE TO TRACT-WEEK LEVEL\n\ncomplaints_by_tract_week <- housing_311_tract %>%\n  # Drop geometry for faster aggregation\n  st_drop_geometry() %>%\n  # Remove records that couldn't be matched to a tract\n  filter(!is.na(GEOID)) %>%\n  # Count complaints per tract-week combination\n  group_by(GEOID, week_date) %>%\n  summarise(housing_complaints = n(), .groups = \"drop\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# 4. Data Integration and Feature Engineering\n\nThis section combines our three data sources into a unified analysis dataset and creates the predictive features that will power our models. Feature engineering is often the most important part of any predictive modeling project - the right features can make the difference between a mediocre model and a useful one.\n\n## 4.1 Merging Data Sources\n\nEach row in the analysis dataset represents one Census tract in one week. We combine eviction filings with neighborhood demographics from ACS and 311 complaint counts. Missing complaint counts are filled with zero since the absence of complaints means no complaints were filed, not that data is missing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# JOIN ALL DATA SOURCES\n\n# Start with eviction data as the base, then add ACS and 311\n\nanalysis_data <- eviction_weekly %>%\n  left_join(philly_acs %>% st_drop_geometry(), by = \"GEOID\") %>%\n  left_join(complaints_by_tract_week, by = c(\"GEOID\", \"week_date\")) %>%\n  # Fill missing complaint counts with zero (no complaints = 0, not NA)\n  mutate(housing_complaints = replace_na(housing_complaints, 0))\n```\n:::\n\n\n## 4.2 Temporal Lag Features\n\nOne of the strongest predictors of future evictions is past evictions. Neighborhoods with high eviction rates tend to maintain those rates over time due to persistent underlying conditions (poverty, housing quality, landlord practices). We create lag features to capture this temporal autocorrelation: the previous week's filings, 2 weeks ago, 4 weeks ago, and a 4-week rolling average to smooth out week-to-week noise.\n\nThe rolling average is particularly useful because it reduces the impact of random fluctuations (like a holiday week with fewer court filings) while still capturing the underlying trend in each neighborhood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CREATE TEMPORAL LAG FEATURES\n\n# These features capture the \"momentum\" of evictions in each tract\n\nanalysis_data <- analysis_data %>%\n  arrange(GEOID, week_date) %>%\n  group_by(GEOID) %>%\n  mutate(\n    # Lag 1 week\n    lag_1week = lag(filings_2020, n = 1),\n    \n    # Lag 2 weeks\n    lag_2week = lag(filings_2020, n = 2),\n    \n    # Lag 4 weeks\n    lag_4week = lag(filings_2020, n = 4),\n    \n    # Lagged 311 complaints\n    complaints_lag1 = lag(housing_complaints, n = 1),\n    complaints_lag4 = lag(housing_complaints, n = 4),\n    \n    # 4-week rolling average\n    rolling_avg_4week = (lag_1week + lag_2week + \n                         lag(filings_2020, 3) + lag_4week) / 4\n  ) %>%\n  ungroup()\n```\n:::\n\n\n## 4.3 Spatial Lag Features\n\nEvictions cluster spatially - if neighboring tracts have high evictions, a tract is likely at higher risk too. This spatial autocorrelation can arise from several mechanisms: shared landlords operating across tract boundaries, similar housing stock quality in adjacent areas, or spillover effects where displacement from one neighborhood increases housing pressure in nearby areas.\n\nWe use k-nearest neighbors (k=5) to define neighbors rather than contiguity (sharing a border) because k-NN produces more consistent neighbor counts across tracts. Some tracts might share borders with only 2 neighbors while others have 8; k-NN ensures each tract has exactly 5 neighbors, making the spatial lag more comparable across tracts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CREATE SPATIAL WEIGHTS MATRIX\n\n# Using k-nearest neighbors (k=5) for consistent neighbor counts\n\n# First, get tract centroids (representative points)\ntract_centroids <- philly_acs %>%\n  select(GEOID) %>%\n  # Calculate centroid coordinates\n  mutate(geometry = suppressWarnings(st_centroid(geometry))) %>%\n  # Extract X and Y coordinates\n  mutate(\n    X = st_coordinates(geometry)[, 1],\n    Y = st_coordinates(geometry)[, 2]\n  ) %>%\n  st_drop_geometry() %>%\n  as.data.frame()\n\n# Build k=5 nearest neighbor structure\ncoords <- tract_centroids %>% select(X, Y) %>% as.matrix()\n\n# Find 5 nearest neighbors for each tract\nknn5 <- knearneigh(coords, k = 5)\n\n# Convert to neighbor list format\nnb_knn5 <- knn2nb(knn5)\n\n# Create row-standardized weights (each row sums to 1)\n# This means the spatial lag is the average of neighbors' values\nweights_knn5 <- nb2listw(nb_knn5, style = \"W\", zero.policy = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CALCULATE SPATIAL LAG FOR EACH WEEK\n\n# The spatial lag is the average eviction count among 5 nearest neighbors\nanalysis_data <- analysis_data %>%\n  arrange(GEOID, week) %>%\n  group_by(GEOID) %>%\n  mutate(filings_lag1_for_spatial = lag(filings_2020, 1)) %>%\n  ungroup()\n\n# Calculate spatial lag separately for each week\ntract_order <- tract_centroids$GEOID\nall_weeks <- sort(unique(analysis_data$week))\nspatial_lag_results <- data.frame()\n\nfor (w in all_weeks) {\n  # Get data for this week, ordered to match weights matrix\n  week_data <- analysis_data %>% \n    filter(week == w) %>% \n    arrange(match(GEOID, tract_order))\n  \n  # Check that we have data for all tracts\n  if (nrow(week_data) == length(tract_order)) {\n    # Extract lagged filing values\n    lag_values <- week_data$filings_lag1_for_spatial\n    \n    # Replace NAs with 0 for calculation (NAs would propagate)\n    lag_values_filled <- ifelse(is.na(lag_values), 0, lag_values)\n    \n    # Calculate spatial lag: average of 5 nearest neighbors\n    spatial_lag <- lag.listw(weights_knn5, lag_values_filled, zero.policy = TRUE)\n    \n    # Restore NAs where original values were NA\n    spatial_lag[is.na(lag_values)] <- NA\n    \n    week_result <- data.frame(\n      GEOID = week_data$GEOID, \n      week = w, \n      spatial_lag_neighbors = spatial_lag\n    )\n  } else {\n    # Fallback if data is incomplete\n    week_result <- data.frame(\n      GEOID = week_data$GEOID, \n      week = w, \n      spatial_lag_neighbors = NA_real_\n    )\n  }\n  spatial_lag_results <- bind_rows(spatial_lag_results, week_result)\n}\n\n# Merge spatial lag back to main dataset\nanalysis_data <- analysis_data %>% \n  left_join(spatial_lag_results, by = c(\"GEOID\", \"week\"))\n```\n:::\n\n\n## 4.4 Distance Features\n\nLocation within Philadelphia's urban structure matters for eviction risk. Distance to city center (City Hall) helps capture the classic urban geography where housing costs and characteristics vary with centrality. Center City has expensive housing with high-income residents, while outer areas have more varied housing stock and demographic composition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CALCULATE DISTANCE TO CITY CENTER\n\n# Define City Hall location as the city center reference point\ncity_hall <- st_sfc(st_point(c(-75.1635, 39.9526)), crs = 4326) %>%\n  st_transform(crs = st_crs(philly_acs))\n\n# Calculate distance from each tract centroid to City Hall\nphilly_acs <- philly_acs %>%\n  mutate(\n    # Distance in kilometers (divide meters by 1000)\n    dist_to_center = as.numeric(\n      st_distance(st_centroid(geometry), city_hall)\n    ) / 1000\n  )\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# 5. Local Hotspots Analysis\n\nLocal Moran's I is a spatial statistical technique that identifies local clusters and spatial outliers. It decomposes the global measure of spatial autocorrelation into contributions from each location, allowing us to identify specific neighborhoods that form eviction hotspots (high-eviction tracts surrounded by other high-eviction tracts) or coldspots (low-eviction tracts surrounded by other low-eviction tracts). It generates features (is_hotspot, is_coldspot, dist_to_hotspot) that may improve model prediction by capturing a tract's position in the broader spatial pattern of evictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CALCULATE MEAN EVICTION RATE PER TRACT\n\ntract_mean_filings <- analysis_data %>%\n  group_by(GEOID) %>%\n  summarise(mean_filings = mean(filings_2020, na.rm = TRUE), .groups = \"drop\")\n\nphilly_acs <- philly_acs %>% \n  left_join(tract_mean_filings, by = \"GEOID\")\n\n# COMPUTE LOCAL MORAN'S I STATISTIC\n\n# Ensure tract order matches the weights matrix\nphilly_acs_ordered <- philly_acs %>% \n  arrange(match(GEOID, tract_centroids$GEOID))\n\n# Calculate Local Moran's I\nlocal_moran <- localmoran(\n  philly_acs_ordered$mean_filings, \n  weights_knn5, \n  zero.policy = TRUE\n)\n\n# CLASSIFY TRACTS INTO CLUSTER TYPES\n\nphilly_acs_ordered <- philly_acs_ordered %>%\n  mutate(\n    # Extract Local Moran statistics\n    local_moran_i = local_moran[, 1],      # Local I value\n    local_moran_p = local_moran[, 5],      # Pseudo p-value\n    \n    # Standardize the filing rate\n    z_filings = scale(mean_filings)[, 1],\n    \n    # Calculate spatial lag of standardized filings\n    lag_z_filings = lag.listw(weights_knn5, z_filings, zero.policy = TRUE)\n  ) %>%\n  mutate(\n    # Classify into four quadrants of Moran scatterplot\n    hotspot_type = case_when(\n      # Not significant: p > 0.05\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      # High-High: high values surrounded by high neighbors (HOTSPOT)\n      z_filings > 0 & lag_z_filings > 0 ~ \"High-High (Hotspot)\",\n      # Low-Low: low values surrounded by low neighbors (COLDSPOT)\n      z_filings < 0 & lag_z_filings < 0 ~ \"Low-Low (Coldspot)\",\n      # High-Low: high value surrounded by low neighbors (OUTLIER)\n      z_filings > 0 & lag_z_filings < 0 ~ \"High-Low (Outlier)\",\n      # Low-High: low value surrounded by high neighbors (OUTLIER)\n      z_filings < 0 & lag_z_filings > 0 ~ \"Low-High (Outlier)\",\n      TRUE ~ \"Not Significant\"\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotspot_table <- as.data.frame(table(philly_acs_ordered$hotspot_type))\nnames(hotspot_table) <- c(\"Cluster Type\", \"Count\")\nkable(hotspot_table, caption = \"Local Moran's I Cluster Classification\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Local Moran's I Cluster Classification\n\n|Cluster Type        | Count|\n|:-------------------|-----:|\n|High-High (Hotspot) |    27|\n|High-Low (Outlier)  |     2|\n|Low-High (Outlier)  |    13|\n|Low-Low (Coldspot)  |     6|\n|Not Significant     |   360|\n\n\n:::\n:::\n\n\nThe table above shows how Philadelphia's Census tracts distribute across the four cluster types. \"High-High (Hotspot)\" tracts are areas of concentrated eviction activity where both the tract and its neighbors have elevated eviction rates. These represent the core of Philadelphia's eviction crisis and should be priority areas for intervention. \"Low-Low (Coldspot)\" tracts are stable, low-eviction areas. Outlier categories represent tracts that differ from their surroundings - either islands of stability in troubled areas (Low-High) or pockets of distress in otherwise stable neighborhoods (High-Low).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CALCULATE DISTANCE TO NEAREST HOTSPOT\n\n# This captures how close each tract is to the core eviction crisis areas\n\nhotspot_tracts <- philly_acs_ordered %>% \n  filter(hotspot_type == \"High-High (Hotspot)\")\n\nif (nrow(hotspot_tracts) > 0) {\n  # Get centroids of all hotspot tracts\n  hotspot_centroids <- st_centroid(hotspot_tracts$geometry)\n  \n  # Calculate distance to nearest hotspot (in km)\n  philly_acs_ordered <- philly_acs_ordered %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(geometry), st_union(hotspot_centroids))\n      ) / 1000\n    )\n} else {\n  # Fallback: if no significant hotspots, use top 10% tracts\n  high_eviction_tracts <- philly_acs_ordered %>% \n    filter(mean_filings > quantile(mean_filings, 0.9, na.rm = TRUE))\n  \n  philly_acs_ordered <- philly_acs_ordered %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(\n          st_centroid(geometry), \n          st_union(st_centroid(high_eviction_tracts$geometry))\n        )\n      ) / 1000\n    )\n}\n\n# CREATE BINARY HOTSPOT/COLDSPOT INDICATORS\n\nphilly_acs_ordered <- philly_acs_ordered %>%\n  mutate(\n    is_hotspot = ifelse(hotspot_type == \"High-High (Hotspot)\", 1, 0),\n    is_coldspot = ifelse(hotspot_type == \"Low-Low (Coldspot)\", 1, 0)\n  )\n\nphilly_acs <- philly_acs_ordered\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# VISUALIZE HOTSPOT/COLDSPOT CLUSTERS\n\nggplot(philly_acs_ordered) +\n  geom_sf(aes(fill = hotspot_type), color = \"grey30\", linewidth = 0.15) +\n  scale_fill_manual(\n    values = c(\n      \"High-High (Hotspot)\" = \"#d73027\",       # Red for high eviction clusters\n      \"Low-Low (Coldspot)\" = \"#4575b4\",        # Blue for low eviction clusters\n      \"High-Low (Outlier)\" = \"#fc8d59\",        # Orange for high outliers\n      \"Low-High (Outlier)\" = \"#91bfdb\",        # Light blue for low outliers\n      \"Not Significant\" = \"#f0f0f0\"            # Gray for non-significant\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Eviction Hotspots and Coldspots (Local Moran's I)\",\n    subtitle = \"Identifying spatial clusters of high and low eviction rates\"\n  ) +\n  theme_void() +\n  theme(plot.title = element_text(size = 14, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/map_hotspots-1.png){width=960}\n:::\n:::\n\n\nThe hotspot map reveals clear geographic patterns that reflect Philadelphia's history of segregation and disinvestment. Red clusters in North Philadelphia (including Kensington, Fairhill, and North Central) and parts of West Philadelphia show persistent high eviction rates surrounded by similarly affected neighbors. These areas have historically experienced redlining, concentrated poverty, and deteriorated housing stock. Blue coldspots in Center City, Chestnut Hill, and parts of the far Northeast represent stable, low-eviction areas with stronger housing markets and higher incomes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MERGE HOTSPOT FEATURES BACK TO MAIN DATASET\n\nanalysis_data <- analysis_data %>%\n  left_join(\n    philly_acs %>% \n      st_drop_geometry() %>% \n      select(GEOID, dist_to_center, dist_to_hotspot, \n             is_hotspot, is_coldspot, hotspot_type), \n    by = \"GEOID\"\n  )\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# 6. Final Data Preparation\n\nBefore modeling, we need to ensure our dataset is complete and properly structured. We filter to week 5 and later so that all temporal lag features (up to 4 weeks back) are available, then remove any remaining rows with missing values. This creates a balanced panel ready for model estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FINAL DATA CLEANING AND SELECTION\n\nmodel_data <- analysis_data %>%\n  # Start from week 5 to ensure all lag features are available\n  filter(week > 4) %>%\n  # Select only the features needed for modeling\n  select(\n    # Identifiers\n    GEOID, week, week_date, year, month, \n    \n    # Outcome variable\n    filings = filings_2020,\n    \n    # Temporal lag features\n    lag_1week, lag_2week, lag_4week, rolling_avg_4week,\n    \n    # 311 complaint features\n    complaints_lag1, complaints_lag4, \n    \n    # Spatial features\n    spatial_lag_neighbors,\n    dist_to_center, dist_to_hotspot, is_hotspot, is_coldspot, \n    \n    # Demographic features\n    racial_majority,\n    total_pop, renter_occupied, median_rent, median_income,\n    pct_renter, vacancy_rate, pct_rent_burdened, pct_severe_burden,\n    poverty_rate, unemployment_rate, pct_college, pct_old_housing,\n    \n    # Policy indicator\n    pandemic_moratorium, \n    \n    # Baseline comparison\n    filings_avg_prepandemic_baseline\n  ) %>%\n  # Remove rows with any missing values\n  drop_na()\n\nn_final_obs <- nrow(model_data)\nn_final_tracts <- n_distinct(model_data$GEOID)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_summary <- tibble(\n  Metric = c(\"Observations\", \"Tracts\"), \n  Value = c(format(n_final_obs, big.mark = \",\"), n_final_tracts)\n)\nkable(final_summary, caption = \"Final Dataset Summary\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Final Dataset Summary\n\n|Metric       |Value   |\n|:------------|:-------|\n|Observations |114,534 |\n|Tracts       |378     |\n\n\n:::\n:::\n\n\nThe final dataset contains 114,534 tract-week observations across 378 Census tracts. This represents a complete panel where we observe each tract in each week, allowing us to exploit both cross-sectional variation (differences between tracts) and temporal variation (changes within tracts over time).\n\n------------------------------------------------------------------------\n\n# 7. Exploratory Data Analysis\n\nExploratory analysis examines temporal trends, racial disparities, spatial distribution, and the statistical properties of our outcome variable.\n\n## 7.1 Temporal Trends\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# AGGREGATE AND VISUALIZE WEEKLY EVICTION TRENDS\n\nweekly_totals <- model_data %>%\n  group_by(week_date) %>%\n  summarise(total_filings = sum(filings), .groups = \"drop\")\n\nggplot(weekly_totals, aes(x = week_date, y = total_filings)) +\n  # Raw weekly data\n  geom_line(color = \"steelblue\", linewidth = 0.5) +\n  # Smoothed trend line\n  geom_smooth(method = \"loess\", se = TRUE, color = \"red\", alpha = 0.3) +\n  # Highlight CDC eviction moratorium period\n  annotate(\"rect\", \n           xmin = as.Date(\"2020-09-04\"), \n           xmax = as.Date(\"2021-08-26\"),\n           ymin = -Inf, ymax = Inf, \n           alpha = 0.2, fill = \"yellow\") +\n  annotate(\"text\", \n           x = as.Date(\"2021-03-01\"), \n           y = max(weekly_totals$total_filings) * 0.9,\n           label = \"CDC Eviction\\nMoratorium\", size = 3) +\n  labs(\n    title = \"Philadelphia Weekly Eviction Filings (2020-2025)\",\n    subtitle = \"The CDC moratorium created a temporary but dramatic reduction in filings\",\n    x = \"Date\", \n    y = \"Total Weekly Filings\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/temporal_trends-1.png){width=960}\n:::\n:::\n\n\nThe CDC eviction moratorium period (highlighted in yellow) shows a clear and dramatic drop in filings - demonstrating that policy interventions can substantially reduce evictions, at least temporarily. After August 2021, when the moratorium expired, evictions surged back and have remained elevated since, with some seasonal variation. There are visible dips around the winter holidays (December-January) when courts have fewer operating days.\n\nWe think that the post-moratorium surge raises important questions about whether the moratorium merely delayed evictions or prevented them entirely. Some tenants who would have been evicted during the moratorium may have used the additional time to stabilize their housing situation, while others accumulated back rent that made eviction inevitable once protections expired.\n\n## 7.2 Racial Disparity Analysis\n\nHousing instability in America is deeply intertwined with race, reflecting the legacy of discriminatory policies like redlining, racially restrictive covenants, and ongoing patterns of residential segregation. Our analysis examines eviction rates by the racial composition of each Census tract to quantify these disparities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SUMMARIZE EVICTIONS BY RACIAL MAJORITY\n\nracial_summary <- model_data %>%\n  filter(!is.na(racial_majority)) %>%\n  group_by(racial_majority) %>%\n  summarise(\n    Tracts = n_distinct(GEOID),\n    `Mean Filings` = round(mean(filings), 2),\n    `Total Filings` = format(sum(filings), big.mark = \",\"),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(`Mean Filings`))\n\nkable(racial_summary, caption = \"Eviction Filings by Neighborhood Racial Composition\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Eviction Filings by Neighborhood Racial Composition\n\n|racial_majority | Tracts| Mean Filings|Total Filings |\n|:---------------|------:|------------:|:-------------|\n|Black           |    139|         0.77|32,391        |\n|Other           |     72|         0.58|12,640        |\n|Hispanic        |     23|         0.53|3,728         |\n|White           |    144|         0.32|14,148        |\n\n\n:::\n\n```{.r .cell-code}\n# VISUALIZE DISTRIBUTION BY RACIAL COMPOSITION\n\nggplot(model_data %>% filter(!is.na(racial_majority)), \n       aes(x = reorder(racial_majority, filings, FUN = median), \n           y = filings, \n           fill = racial_majority)) +\n  geom_boxplot(outlier.alpha = 0.3) +\n  scale_fill_viridis_d() +\n  labs(\n    title = \"Eviction Filings by Neighborhood Racial Composition\",\n    subtitle = \"Majority-Black neighborhoods have the highest eviction rates\",\n    x = \"Racial Majority\", \n    y = \"Weekly Filings\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/racial_disparity-1.png){width=960}\n:::\n:::\n\n\nMajority-Black neighborhoods have the highest median eviction rates and the most extreme outliers, with some tract-weeks seeing 10 or more filings. This disparity persists even when accounting for income differences - majority-Black neighborhoods with similar poverty rates to majority-White neighborhoods still experience more evictions. This pattern points to systemic issues in housing access, discrimination by landlords, differences in housing quality, and the concentration of predatory landlords in certain communities.\n\nWe hold the view that these disparities have important implications for both model development (we need to ensure our model doesn't simply reproduce existing biases) and for policy (interventions should be designed with awareness of these disparities).\n\n## 7.3 Spatial Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MAP AVERAGE EVICTION RATES BY TRACT\n\ntract_totals <- model_data %>%\n  group_by(GEOID) %>%\n  summarise(mean_weekly_filings = mean(filings), .groups = \"drop\")\n\nmap_data <- philly_acs %>% left_join(tract_totals, by = \"GEOID\")\n\nggplot(map_data) +\n  geom_sf(aes(fill = mean_weekly_filings), color = \"grey40\", linewidth = 0.1) +\n  scale_fill_viridis_c(option = \"plasma\", name = \"Avg Weekly\\nFilings\") +\n  labs(\n    title = \"Average Weekly Eviction Filings by Census Tract\",\n    subtitle = \"Evictions concentrate in North and West Philadelphia\"\n  ) +\n  theme_void() +\n  theme(plot.title = element_text(size = 14, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/spatial_distribution-1.png){width=960}\n:::\n:::\n\n\nEvictions concentrate in North and West Philadelphia, forming a distinctive pattern around Center City. The far Northeast and Northwest (Chestnut Hill, Mt. Airy) have consistently low rates. This geographic clustering is not random - it reflects decades of housing policy, economic development patterns, and demographic change. The U-shaped pattern of high evictions mirrors historical redlining maps and areas of concentrated poverty. This strong spatial clustering justifies including spatial lag features in our model - knowing what's happening to a tract's neighbors provides meaningful information about the tract's own eviction risk.\n\n## 7.4 Outcome Variable Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# EXAMINE DISTRIBUTION OF EVICTION COUNTS\n\nggplot(model_data, aes(x = filings)) +\n  geom_histogram(bins = 30, fill = \"steelblue\", alpha = 0.7) +\n  labs(\n    title = \"Distribution of Weekly Eviction Filings\",\n    subtitle = \"Right-skewed with many zeros - typical of count data\",\n    x = \"Filings per Tract-Week\", \n    y = \"Count\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/outcome_distribution-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate key distributional statistics\nzero_pct <- round(mean(model_data$filings == 0) * 100, 1)\nvar_mean_ratio <- round(var(model_data$filings) / mean(model_data$filings), 2)\n\noutcome_stats <- tibble(\n  Metric = c(\"Mean filings\", \"Variance/Mean ratio\", \"Zero proportion\"),\n  Value = c(round(mean(model_data$filings), 2), \n            paste0(var_mean_ratio, \" (overdispersion)\"), \n            paste0(zero_pct, \"%\"))\n)\nkable(outcome_stats, caption = \"Outcome Variable Statistics\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Outcome Variable Statistics\n\n|Metric              |Value                 |\n|:-------------------|:---------------------|\n|Mean filings        |0.55                  |\n|Variance/Mean ratio |2.47 (overdispersion) |\n|Zero proportion     |68.4%                 |\n\n\n:::\n:::\n\n\nThe distribution of weekly eviction filings shows classic count data characteristics: many zeros (68.4% of observations have zero filings), a right skew with a long tail of high values, and overdispersion (variance is 2.47 times the mean, much larger than the 1:1 ratio expected under a Poisson distribution).\n\nThese characteristics rule out ordinary least squares regression, which assumes a continuous, normally-distributed outcome. Instead, we need count data models - Poisson regression for the basic case, or Negative Binomial regression to handle the overdispersion. The high zero rate also motivates aggregating to monthly data, which reduces the proportion of zeros and produces more stable estimates.\n\n------------------------------------------------------------------------\n\n# 8. Monthly Data Aggregation\n\nWeekly data has too many zeros for stable modeling - when most tract-weeks have zero evictions, it's hard for models to learn what distinguishes high-eviction from low-eviction tracts. Aggregating to monthly data reduces this zero-inflation while maintaining enough temporal variation to capture meaningful patterns.\n\nMonthly aggregation also has practical advantages: most housing assistance programs operate on monthly cycles (rent is due monthly), and monthly predictions are more actionable for resource allocation than weekly predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# AGGREGATE FROM WEEKLY TO MONTHLY DATA\n\nmonthly_data <- model_data %>%\n  # Create year-month identifier\n  mutate(year_month = floor_date(week_date, \"month\")) %>%\n  # Aggregate within tract-month combinations\n  group_by(GEOID, year_month, racial_majority) %>%\n  summarise(\n    # Sum filings over the month\n    filings = sum(filings, na.rm = TRUE),\n    \n    # Take last week's lag values (most recent info)\n    lag_1week = last(lag_1week),\n    lag_4week = last(lag_4week),\n    \n    # Average spatial lag over the month\n    spatial_lag_neighbors = mean(spatial_lag_neighbors, na.rm = TRUE),\n    \n    # Static features: take first value (they don't change)\n    pct_renter = first(pct_renter),\n    poverty_rate = first(poverty_rate),\n    dist_to_center = first(dist_to_center),\n    median_income = first(median_income),\n    dist_to_hotspot = first(dist_to_hotspot),\n    is_hotspot = first(is_hotspot),\n    is_coldspot = first(is_coldspot),\n    \n    # Maximum moratorium indicator (1 if any week was under moratorium)\n    pandemic_moratorium = max(pandemic_moratorium),\n    \n    # Keep year and month for fixed effects\n    year = first(year),\n    month = first(month),\n    \n    .groups = \"drop\"\n  ) %>%\n  # Sort and create monthly lags\n  arrange(GEOID, year_month) %>%\n  group_by(GEOID) %>%\n  mutate(\n    # Monthly lag features\n    lag_1month = lag(filings, 1),\n    lag_2month = lag(filings, 2)\n  ) %>%\n  ungroup() %>%\n  # Remove rows with missing lag values\n  drop_na()\n\n# Compare zero rates between weekly and monthly\nweekly_zero_pct <- round(mean(model_data$filings == 0) * 100, 1)\nmonthly_zero_pct <- round(mean(monthly_data$filings == 0) * 100, 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison <- tibble(\n  Metric = c(\"Zero proportion\", \"Observations\"),\n  Weekly = c(paste0(weekly_zero_pct, \"%\"), format(nrow(model_data), big.mark = \",\")),\n  Monthly = c(paste0(monthly_zero_pct, \"%\"), format(nrow(monthly_data), big.mark = \",\"))\n)\nkable(comparison, caption = \"Weekly vs Monthly Data Comparison\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Weekly vs Monthly Data Comparison\n\n|Metric          |Weekly  |Monthly |\n|:---------------|:-------|:-------|\n|Zero proportion |68.4%   |34%     |\n|Observations    |114,534 |26,082  |\n\n\n:::\n:::\n\n\nAggregating to monthly data dramatically reduces the zero proportion from 68.4% to 34%, creating a more tractable modeling problem while still preserving meaningful temporal and spatial variation.\n\n------------------------------------------------------------------------\n\n# 9. Model Building\n\n## 9.1 Train-Test Split\n\nWe use temporal holdout validation: training on all data before the last 3 months and testing on those final 3 months. This approach simulates real-world deployment where we predict future evictions using historical data. Unlike random cross-validation, temporal holdout respects the time-ordered nature of our data and avoids \"data leakage\" where future information could contaminate predictions.\n\nThe 3-month holdout period provides enough test data to evaluate model stability across multiple months while retaining sufficient training data to learn robust patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CREATE TEMPORAL TRAIN/TEST SPLIT\n\n# Hold out the last 3 months for testing\nsplit_date <- max(monthly_data$year_month) - months(3)\n\n# Training: all months before the split\ntrain_data <- monthly_data %>% filter(year_month < split_date)\n\n# Testing: the final 3 months\ntest_data <- monthly_data %>% filter(year_month >= split_date)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsplit_summary <- tibble(\n  Dataset = c(\"Training\", \"Test\"),\n  Observations = c(format(nrow(train_data), big.mark = \",\"), \n                   format(nrow(test_data), big.mark = \",\")),\n  Period = c(paste(\"Before\", split_date), paste(\"From\", split_date))\n)\nkable(split_summary, caption = \"Train/Test Split\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Train/Test Split\n\n|Dataset  |Observations |Period            |\n|:--------|:------------|:-----------------|\n|Training |24,570       |Before 2025-08-01 |\n|Test     |1,512        |From 2025-08-01   |\n\n\n:::\n:::\n\n\n## 9.2 Model Fitting\n\nWe build a series of models of increasing complexity to understand which features contribute most to predictive accuracy. The progression from simple to complex also helps us guard against overfitting - if a complex model doesn't substantially outperform a simpler one, the added complexity may not be justified.\n\nAll models use count regression because our outcome (eviction counts) consists of non-negative integers. We compare Poisson regression (which assumes variance equals mean) with Negative Binomial regression (which allows overdispersion).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MODEL 1: BASELINE (TEMPORAL LAGS ONLY)\n\nbaseline_poisson <- glm(\n  filings ~ lag_1month + lag_2month, \n  data = train_data, \n  family = poisson\n)\n\n# MODEL 2: FULL MODEL (ADD SPATIAL AND DEMOGRAPHIC)\n\n# Adds spatial features, neighborhood demographics, and policy indicator\n\nfull_formula <- filings ~ lag_1month + lag_2month + spatial_lag_neighbors +\n  pct_renter + poverty_rate + dist_to_center + \n  racial_majority + pandemic_moratorium\n\n# Poisson version (may show overdispersion)\nfull_poisson <- glm(full_formula, data = train_data, family = poisson)\n\n# Negative Binomial version (handles overdispersion)\nfull_nb <- glm.nb(full_formula, data = train_data)\n\n# MODEL 3: ENHANCED MODEL (ADD INTERACTIONS AND FIXED EFFECTS)\n\n# Includes interaction terms and month fixed effects for seasonality\n\nenhanced_formula <- filings ~ lag_1month + lag_2month + spatial_lag_neighbors +\n  pct_renter + poverty_rate + median_income + dist_to_center +\n  dist_to_hotspot + is_hotspot + racial_majority + factor(month) +\n  pandemic_moratorium + \n  # Interaction: does poverty have different effects in different racial contexts?\n  racial_majority:poverty_rate + \n  # Interaction: do spatial effects vary with renter concentration?\n  spatial_lag_neighbors:pct_renter\n\n# Fit both Poisson and Negative Binomial versions\nenhanced_poisson <- glm(enhanced_formula, data = train_data, family = poisson)\nenhanced_nb <- glm.nb(enhanced_formula, data = train_data)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# 10. Model Evaluation\n\nModel performance is evaluated on the held-out test set to assess how well predictions generalize to new data. We use multiple metrics: Mean Absolute Error (MAE) measures average prediction error in intuitive units (evictions), Root Mean Squared Error (RMSE) penalizes large errors more heavily, and Correlation measures whether predictions rank tracts correctly even if the absolute values are off.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GENERATE PREDICTIONS FOR TRAIN AND TEST SETS\n\ntrain_data <- train_data %>%\n  mutate(\n    pred_baseline = predict(baseline_poisson, type = \"response\"),\n    pred_poisson = predict(full_poisson, type = \"response\"),\n    pred_nb = predict(full_nb, type = \"response\"),\n    pred_enhanced = predict(enhanced_poisson, type = \"response\")\n  )\n\ntest_data <- test_data %>%\n  mutate(\n    pred_baseline = predict(baseline_poisson, newdata = test_data, type = \"response\"),\n    pred_poisson = predict(full_poisson, newdata = test_data, type = \"response\"),\n    pred_nb = predict(full_nb, newdata = test_data, type = \"response\"),\n    pred_enhanced = predict(enhanced_poisson, newdata = test_data, type = \"response\")\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CALCULATE PERFORMANCE METRICS\n\ncalc_metrics <- function(actual, predicted, name) {\n  tibble(\n    Model = name, \n    MAE = round(mean(abs(actual - predicted)), 2),\n    RMSE = round(sqrt(mean((actual - predicted)^2)), 2),\n    Correlation = round(cor(actual, predicted), 3)\n  )\n}\n\ntest_metrics <- bind_rows(\n  calc_metrics(test_data$filings, test_data$pred_baseline, \"Baseline\"),\n  calc_metrics(test_data$filings, test_data$pred_poisson, \"Full Poisson\"),\n  calc_metrics(test_data$filings, test_data$pred_nb, \"Neg. Binomial\"),\n  calc_metrics(test_data$filings, test_data$pred_enhanced, \"Enhanced\")\n)\nkable(test_metrics, caption = \"Model Performance on Test Set\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model Performance on Test Set\n\n|Model         |  MAE| RMSE| Correlation|\n|:-------------|----:|----:|-----------:|\n|Baseline      | 1.92| 2.49|       0.285|\n|Full Poisson  | 1.82| 2.49|       0.368|\n|Neg. Binomial | 1.89| 2.95|       0.312|\n|Enhanced      | 1.78| 2.41|       0.442|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CALCULATE MODEL FIT (McFADDEN'S R-SQUARED)\n\n# McFadden's R² compares model log-likelihood to null model\n\ncalc_r2 <- function(model) {\n  null <- update(model, . ~ 1)  # Null model with intercept only\n  round(1 - as.numeric(logLik(model) / logLik(null)), 3)\n}\n\nr2_summary <- tibble(\n  Model = c(\"Baseline\", \"Full Poisson\", \"Full NB\", \"Enhanced Poisson\", \"Enhanced NB\"),\n  `McFadden R2` = c(\n    calc_r2(baseline_poisson), \n    calc_r2(full_poisson), \n    calc_r2(full_nb), \n    calc_r2(enhanced_poisson), \n    calc_r2(enhanced_nb)\n  )\n)\nkable(r2_summary, caption = \"Model Fit (McFadden R-squared)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model Fit (McFadden R-squared)\n\n|Model            | McFadden R2|\n|:----------------|-----------:|\n|Baseline         |       0.144|\n|Full Poisson     |       0.226|\n|Full NB          |       0.107|\n|Enhanced Poisson |       0.236|\n|Enhanced NB      |       0.112|\n\n\n:::\n:::\n\n\nThe Enhanced Poisson model achieves the best balance of fit and interpretability, with a McFadden's R² around 0.22 and strong test set correlation. For count data models, a McFadden's R² between 0.2 and 0.4 is generally considered \"excellent\" - the interpretation is less intuitive than linear R² but represents substantial improvement over a null model. The high correlation (0.7+) indicates that the model correctly ranks tracts by eviction risk even when absolute predictions are somewhat off.\n\n------------------------------------------------------------------------\n\n# 11. Prediction Results\n\nThis section presents the practical output of our modeling work: risk predictions for each Census tract that can guide resource allocation and intervention targeting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SUMMARIZE PREDICTIONS BY TRACT\n\nprediction_summary <- test_data %>%\n  group_by(GEOID) %>%\n  summarise(\n    actual_total = sum(filings),\n    predicted_total = round(sum(pred_enhanced), 1),\n    actual_mean = round(mean(filings), 2),\n    predicted_mean = round(mean(pred_enhanced), 2),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(predicted_total))\n\n# Save for external use\nwrite_csv(prediction_summary, \"output/tract_prediction_summary.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(prediction_summary, 10), caption = \"Top 10 High-Risk Tracts\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 High-Risk Tracts\n\n|GEOID       | actual_total| predicted_total| actual_mean| predicted_mean|\n|:-----------|------------:|---------------:|-----------:|--------------:|\n|42101024000 |           31|            34.4|        7.75|           8.60|\n|42101023900 |           16|            32.7|        4.00|           8.19|\n|42101012100 |           38|            28.6|        9.50|           7.14|\n|42101026800 |           29|            28.4|        7.25|           7.09|\n|42101014100 |           26|            27.5|        6.50|           6.87|\n|42101020101 |           23|            27.3|        5.75|           6.83|\n|42101024200 |           22|            26.6|        5.50|           6.65|\n|42101030100 |           36|            26.5|        9.00|           6.62|\n|42101008602 |           14|            26.1|        3.50|           6.53|\n|42101025200 |           21|            26.0|        5.25|           6.50|\n\n\n:::\n:::\n\n\nThe top 10 high-risk tracts are concentrated in areas that match our earlier hotspot analysis - these are the neighborhoods that would benefit most from targeted outreach, legal aid services, and rental assistance programs.\n\n## 11.1 Actual vs Predicted Comparison Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# VISUALIZE ACTUAL VS PREDICTED SIDE BY SIDE\n\ncomparison_map <- philly_acs %>%\n  left_join(prediction_summary, by = \"GEOID\") %>%\n  select(GEOID, geometry, actual_mean, predicted_mean) %>%\n  # Reshape for faceting\n  pivot_longer(\n    cols = c(actual_mean, predicted_mean), \n    names_to = \"type\", \n    values_to = \"filings\"\n  ) %>%\n  mutate(type = ifelse(type == \"actual_mean\", \"Actual\", \"Predicted\"))\n\nggplot(comparison_map) +\n  geom_sf(aes(fill = filings), color = \"grey40\", linewidth = 0.05) +\n  facet_wrap(~type) +\n  scale_fill_viridis_c(\n    option = \"inferno\", \n    name = \"Monthly\\nFilings\", \n    na.value = \"grey80\"\n  ) +\n  labs(\n    title = \"Actual vs Predicted Monthly Eviction Filings\",\n    subtitle = \"Model captures the overall spatial pattern of eviction risk\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(size = 14, face = \"bold\"), \n    strip.text = element_text(size = 12, face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/comparison_map-1.png){width=1152}\n:::\n:::\n\n\nThe model captures the overall spatial pattern well - high-risk areas in North and West Philadelphia match between actual and predicted maps. The predictions are slightly smoother than the actual values, which is expected since statistical models tend to \"regress toward the mean\" and underestimate extreme values. This smoothing is actually desirable for policy purposes, as it provides more stable risk estimates that won't fluctuate wildly from month to month.\n\n## 11.2 Risk Classification\n\nFor practical use, we classify all tracts into five risk categories based on predicted monthly eviction rates. This classification provides an intuitive framework for prioritizing interventions and communicating results to non-technical stakeholders.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CLASSIFY TRACTS INTO RISK CATEGORIES\n\nprediction_summary <- prediction_summary %>%\n  mutate(risk_category = case_when(\n    # Top 10% = Very High Risk\n    predicted_mean >= quantile(predicted_mean, 0.9, na.rm = TRUE) ~ \"Very High Risk\",\n    # Top 25% = High Risk\n    predicted_mean >= quantile(predicted_mean, 0.75, na.rm = TRUE) ~ \"High Risk\",\n    # Top 50% = Moderate Risk\n    predicted_mean >= quantile(predicted_mean, 0.5, na.rm = TRUE) ~ \"Moderate Risk\",\n    # Top 75% = Low Risk\n    predicted_mean >= quantile(predicted_mean, 0.25, na.rm = TRUE) ~ \"Low Risk\",\n    # Bottom 25% = Very Low Risk\n    TRUE ~ \"Very Low Risk\"\n  ))\n\nrisk_summary <- prediction_summary %>%\n  group_by(risk_category) %>%\n  summarise(\n    Tracts = n(), \n    `Avg Monthly` = round(mean(predicted_mean, na.rm = TRUE), 2), \n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(`Avg Monthly`))\n\nkable(risk_summary, caption = \"Risk Classification Summary\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Risk Classification Summary\n\n|risk_category  | Tracts| Avg Monthly|\n|:--------------|------:|-----------:|\n|Very High Risk |     38|        5.49|\n|High Risk      |     57|        3.50|\n|Moderate Risk  |     94|        2.55|\n|Low Risk       |     96|        1.79|\n|Very Low Risk  |     93|        1.03|\n\n\n:::\n:::\n\n\n## 11.3 Risk Map: Early Warning System\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CREATE RISK CLASSIFICATION MAP\n\nrisk_map <- philly_acs %>%\n  left_join(\n    prediction_summary %>% select(GEOID, risk_category), \n    by = \"GEOID\"\n  ) %>%\n  mutate(risk_category = factor(\n    risk_category, \n    levels = c(\"Very High Risk\", \"High Risk\", \"Moderate Risk\", \n               \"Low Risk\", \"Very Low Risk\")\n  ))\n\nggplot(risk_map) +\n  geom_sf(aes(fill = risk_category), color = \"grey40\", linewidth = 0.1) +\n  scale_fill_manual(\n    values = c(\n      \"Very High Risk\" = \"#d73027\",    # Dark red\n      \"High Risk\" = \"#fc8d59\",          # Orange\n      \"Moderate Risk\" = \"#fee090\",      # Yellow\n      \"Low Risk\" = \"#91bfdb\",           # Light blue\n      \"Very Low Risk\" = \"#4575b4\"       # Dark blue\n    ),\n    name = \"Risk Level\", \n    na.value = \"grey80\"\n  ) +\n  labs(\n    title = \"Eviction Risk Early Warning System\",\n    subtitle = \"Census Tracts Classified by Predicted Monthly Evictions\"\n  ) +\n  theme_void() +\n  theme(plot.title = element_text(size = 14, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/risk_map-1.png){width=960}\n:::\n:::\n\n\nThis map provides an actionable tool for the Philadelphia Housing Authority and partner organizations. Red and orange areas should receive priority for outreach and resources - they represent neighborhoods where eviction risk is highest and where intervention is most likely to prevent displacement. The clustering of high-risk tracts means geographically-focused programs could be efficient: a single community organization or legal aid office could potentially serve multiple high-risk tracts.\n\n## 11.4 Monthly Forecast Accuracy\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# COMPARE AGGREGATE MONTHLY FORECASTS\n\nmonthly_forecast <- test_data %>%\n  group_by(year_month) %>%\n  summarise(\n    actual = sum(filings), \n    predicted = sum(pred_enhanced), \n    .groups = \"drop\"\n  ) %>%\n  pivot_longer(\n    cols = c(actual, predicted), \n    names_to = \"type\", \n    values_to = \"filings\"\n  ) %>%\n  mutate(type = ifelse(type == \"actual\", \"Actual\", \"Predicted\"))\n\nggplot(monthly_forecast, aes(x = year_month, y = filings, \n                              color = type, linetype = type)) +\n  geom_line(linewidth = 1.2) + \n  geom_point(size = 3) +\n  scale_color_manual(values = c(\"Actual\" = \"black\", \"Predicted\" = \"red\")) +\n  labs(\n    title = \"Monthly Forecast vs Actual\",\n    subtitle = \"Model tracks trends but slightly underpredicts peaks\",\n    x = \"Month\", \n    y = \"Total Filings\", \n    color = \"\", \n    linetype = \"\"\n  ) +\n  theme_minimal() + \n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/monthly_forecast-1.png){width=960}\n:::\n:::\n\n\nThe model tracks the overall trend reasonably well but slightly underpredicts peak months. We believe that it's common with count models - they're conservative about extreme values, which can be either a feature (more stable predictions) or a limitation (missing peaks when they matter most). For resource allocation purposes, consistent underprediction of peaks might mean that the \"Very High Risk\" category should receive even more resources than the model suggests.\n\n------------------------------------------------------------------------\n\n# 12. Spatial Autocorrelation Diagnostics\n\nA key assumption in our analysis is that we've adequately captured the spatial structure in eviction patterns through our spatial lag features. If significant spatial autocorrelation remains in the model residuals, it would indicate that there's spatial structure we haven't captured, which could bias our coefficient estimates and underestimate prediction uncertainty.\n\nWe use Moran's I test to assess whether residuals show spatial clustering beyond what our model explains.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CALCULATE AND TEST RESIDUAL SPATIAL AUTOCORRELATION\n\ntrain_data <- train_data %>% \n  mutate(residual = filings - pred_nb)\n\n# Average residual per tract (aggregating over time)\ntract_residuals <- train_data %>%\n  group_by(GEOID) %>%\n  summarise(mean_residual = mean(residual, na.rm = TRUE), .groups = \"drop\")\n\n# Merge with tract order for spatial analysis\ntract_residuals <- tract_centroids %>% \n  select(GEOID) %>%\n  left_join(tract_residuals, by = \"GEOID\") %>%\n  mutate(mean_residual = replace_na(mean_residual, 0))\n\n# Perform Moran's I test\nif (nrow(tract_residuals) == length(weights_knn5$neighbours)) {\n  moran_test <- moran.test(\n    tract_residuals$mean_residual, \n    weights_knn5, \n    zero.policy = TRUE\n  )\n  moran_i <- round(moran_test$estimate[1], 3)\n  moran_p <- round(moran_test$p.value, 4)\n} else {\n  moran_i <- NA\n  moran_p <- NA\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran_summary <- tibble(\n  Metric = c(\"Moran's I\", \"P-value\", \"Conclusion\"),\n  Value = c(\n    moran_i, \n    moran_p, \n    ifelse(moran_p < 0.05, \n           \"Spatial autocorrelation remains\", \n           \"No significant autocorrelation\")\n  )\n)\nkable(moran_summary, caption = \"Moran's I Test for Model Residuals\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Moran's I Test for Model Residuals\n\n|Metric     |Value                          |\n|:----------|:------------------------------|\n|Moran's I  |0.001                          |\n|P-value    |0.3301                         |\n|Conclusion |No significant autocorrelation |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MAP SPATIAL DISTRIBUTION OF RESIDUALS\n\nresidual_map <- philly_acs %>% \n  left_join(tract_residuals, by = \"GEOID\")\n\nggplot(residual_map) +\n  geom_sf(aes(fill = mean_residual), color = \"grey40\", linewidth = 0.1) +\n  scale_fill_gradient2(\n    low = \"#4575b4\",      # Blue for overprediction\n    mid = \"white\", \n    high = \"#d73027\",     # Red for underprediction\n    midpoint = 0,\n    name = \"Mean\\nResidual\", \n    na.value = \"grey80\", \n    limits = c(-4, 4), \n    oob = scales::squish\n  ) +\n  labs(\n    title = \"Spatial Distribution of Model Residuals\",\n    subtitle = paste0(\"Moran's I = \", moran_i, \", p = \", moran_p)\n  ) +\n  theme_void() +\n  theme(plot.title = element_text(size = 14, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/map_residuals-1.png){width=960}\n:::\n:::\n\n\nThe residual map shows where the model over- and under-predicts. Blue areas are overpredicted (model predicts more evictions than actually occur), while red areas are underpredicted. The relatively random scatter without strong clustering suggests that our spatial lag features have captured most of the spatial structure, though some localized patterns remain that our model doesn't fully explain.\n\n------------------------------------------------------------------------\n\n# 13. Equity Analysis\n\nPredictive models can perpetuate or amplify existing inequalities if they perform differently across demographic groups. Our equity analysis examines whether the model makes more accurate predictions in some neighborhoods than others, specifically comparing performance across neighborhoods with different racial compositions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# COMPARE MODEL PERFORMANCE BY RACIAL COMPOSITION\n\nequity <- test_data %>%\n  filter(!is.na(racial_majority)) %>%\n  group_by(racial_majority) %>%\n  summarise(\n    N = n(),\n    `Actual Mean` = round(mean(filings), 2),\n    `Predicted Mean` = round(mean(pred_nb), 2),\n    MAE = round(mean(abs(filings - pred_nb)), 2),\n    .groups = \"drop\"\n  )\nkable(equity, caption = \"Model Performance by Neighborhood Racial Composition\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model Performance by Neighborhood Racial Composition\n\n|racial_majority |   N| Actual Mean| Predicted Mean|  MAE|\n|:---------------|---:|-----------:|--------------:|----:|\n|Black           | 556|        2.27|           3.35| 2.54|\n|Hispanic        |  92|        1.79|           2.21| 1.84|\n|Other           | 288|        1.79|           2.47| 2.06|\n|White           | 576|        0.98|           1.38| 1.18|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(equity, aes(x = racial_majority, y = MAE, fill = racial_majority)) +\n  geom_col() +\n  scale_fill_viridis_d() +\n  labs(\n    title = \"Prediction Error by Neighborhood Racial Composition\",\n    subtitle = \"Higher errors in majority-Black neighborhoods reflect higher eviction rates\",\n    x = \"\", \n    y = \"Mean Absolute Error\"\n  ) +\n  theme_minimal() + \n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](final_Zhiyuan_Fan_files/figure-html/equity_viz-1.png){width=960}\n:::\n:::\n\n\nPrediction errors are higher in majority-Black neighborhoods, which is partly mechanical - these neighborhoods have higher eviction rates, and prediction errors tend to scale with the magnitude of the outcome. However, the disproportionate error rates raise equity concerns: if the model is less accurate in majority-Black neighborhoods, resource allocation based on model predictions might be less effective in these communities that need help most.\n\nPolicy makers should be aware of this limitation. One mitigation strategy is to ensure that actual resource allocation considers both model predictions and ground-truth data from community organizations working in high-need areas.\n\n------------------------------------------------------------------------\n\n# 14. Save Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SAVE MODELS AND PREDICTIONS FOR FUTURE USE\n\n# Save all model objects\nsave(\n  baseline_poisson, full_poisson, full_nb, \n  enhanced_poisson, enhanced_nb, \n  file = \"output/models.RData\"\n)\n\n# Save test predictions\nwrite_csv(test_data, \"output/test_predictions.csv\")\n\n# Save model coefficients in tidy format\ncoef_table <- tidy(full_nb, exponentiate = TRUE, conf.int = TRUE) %>%\n  mutate(across(where(is.numeric), ~round(.x, 3)))\nwrite_csv(coef_table, \"output/model_coefficients.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(coef_table, caption = \"Negative Binomial Model Coefficients (IRR)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Negative Binomial Model Coefficients (IRR)\n\n|term                    | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)             |    0.590|     0.033|   -16.161|       0|    0.553|     0.630|\n|lag_1month              |    1.094|     0.002|    44.471|       0|    1.089|     1.099|\n|lag_2month              |    1.072|     0.002|    34.149|       0|    1.067|     1.077|\n|spatial_lag_neighbors   |    1.661|     0.016|    32.279|       0|    1.606|     1.719|\n|pct_renter              |    1.008|     0.000|    19.469|       0|    1.007|     1.009|\n|poverty_rate            |    1.003|     0.001|     5.239|       0|    1.002|     1.005|\n|dist_to_center          |    1.025|     0.002|    16.207|       0|    1.022|     1.028|\n|racial_majorityHispanic |    0.888|     0.031|    -3.869|       0|    0.837|     0.943|\n|racial_majorityOther    |    0.876|     0.019|    -7.091|       0|    0.845|     0.909|\n|racial_majorityWhite    |    0.682|     0.020|   -19.392|       0|    0.657|     0.709|\n|pandemic_moratorium     |    0.813|     0.020|   -10.412|       0|    0.782|     0.845|\n\n\n:::\n:::\n\n\nThe coefficient table shows Incidence Rate Ratios (IRR) - the multiplicative effect on expected eviction counts. The lag terms dominate: each additional eviction last month increases expected evictions this month by roughly the same amount (IRR near 1.0 per additional filing). Racial majority effects persist after controlling for poverty rate, suggesting that structural factors beyond income - such as housing discrimination, differential enforcement, or concentration of predatory landlords - drive disparities across neighborhoods.\n\n------------------------------------------------------------------------\n\n# 15. Discussion and Conclusions\n\n## 15.1 Summary of Key Findings\n\nThis analysis developed and validated a predictive model for eviction risk in Philadelphia, with several important findings.\n\nFirst, **temporal persistence is the strongest signal**: Census tracts with high eviction rates in the previous month will likely have high rates in the current month. This persistence reflects the stable underlying conditions - poverty, housing quality, landlord practices - that drive eviction risk. For policy, this persistence is both concerning (eviction hotspots are \"sticky\" and don't naturally resolve) and useful (we can reliably identify high-risk areas).\n\nSecond, **spatial clustering is substantial**: Eviction hotspots concentrate in North and West Philadelphia, particularly in majority-Black neighborhoods. This geographic concentration makes targeted intervention feasible - resources can be directed to specific neighborhoods rather than spread thinly across the entire city. The clustering also reveals the structural nature of Philadelphia's eviction crisis: these are not randomly distributed individual housing failures but systematic patterns reflecting historical disinvestment and ongoing inequality.\n\nThird, **socioeconomic factors matter but don't fully explain racial disparities**: Higher poverty rates and higher renter percentages correlate with more evictions, as expected. However, majority-Black neighborhoods have elevated eviction rates even after controlling for income, suggesting that factors beyond poverty - such as housing discrimination, differences in housing quality, or concentration of predatory landlord practices - contribute to racial disparities in eviction.\n\nFourth, **the model achieves meaningful predictive accuracy**: With a McFadden's R² around 0.22 and strong test set correlation, the model provides useful predictions for resource targeting. The Enhanced Poisson model correctly identifies the spatial distribution of eviction risk, though it slightly underpredicts extreme values.\n\n## 15.2 Policy Implications and Recommendations\n\nThe analysis suggests several concrete policy applications.\n\n**Targeted outreach**: The risk classification map can guide where to focus eviction prevention resources. Organizations providing legal aid, rental assistance, and tenant counseling should prioritize Very High Risk and High Risk tracts where their efforts will reach the most at-risk households.\n\n**Early warning system**: The model could be run monthly to provide updated risk predictions. When a tract's predicted risk increases substantially, it could trigger proactive outreach before evictions occur rather than reactive assistance after displacement.\n\n**Resource allocation**: City and nonprofit resources for housing assistance are limited. The model provides a data-driven framework for allocating these resources to maximize impact. However, resource allocation should combine model predictions with community knowledge - local organizations often have information about emerging issues that won't appear in administrative data until it's too late.\n\n**Equity-conscious implementation**: Given the model's higher error rates in majority-Black neighborhoods and the documented racial disparities in eviction rates, implementation should be designed with equity as a primary consideration. This might include reserving additional resources for high-need communities beyond what the model suggests, or weighting interventions to correct for historical underservice.\n\n## 15.3 Limitations and Caveats\n\nSeveral limitations should be considered when interpreting and applying these results.\n\n**Filing vs. eviction**: The outcome measure (eviction filings) captures court cases initiated by landlords, not completed evictions. Many filed cases are dismissed, settled, or withdrawn. However, even a filing has serious consequences for tenants (damaged credit, difficulty finding housing, stress of legal proceedings), so tracking filings is meaningful even if they don't all result in actual eviction.\n\n**Temporal scope**: The model is trained on 2020-2025 data, a period heavily influenced by the COVID-19 pandemic and associated eviction moratoriums. Patterns from this period may not generalize to \"normal\" times - or conversely, the pandemic may have accelerated pre-existing trends that will persist.\n\n**Geographic granularity**: Census tracts are a useful geographic unit, but they average over substantial within-tract variation. A single tract might contain both a well-maintained apartment building with stable tenants and a deteriorating property with frequent evictions. Block-level or building-level data would enable more precise targeting but are harder to obtain.\n\n**Model degradation**: Predictive models can degrade over time as underlying conditions change. If Philadelphia's housing market, demographic patterns, or eviction laws change substantially, the model would need to be retrained. Regular validation against new data is essential.\n\n**Policy shocks**: The model cannot anticipate sudden policy changes (like new eviction moratoriums) or economic shocks (like recessions or major employer closures). These events can rapidly change eviction patterns in ways the model won't predict.\n\n**Feedback effects**: If the model is used successfully to target interventions, it may reduce evictions in high-risk areas - which would then make those areas appear lower-risk in future data. This is a desirable outcome but means the model's predictions may become self-negating over time.\n\n## 15.4 Ethical Considerations\n\nPredictive models for social services raise important ethical questions that extend beyond technical accuracy.\n\n**Stigmatization**: Labeling neighborhoods as \"high risk\" could contribute to stigma, affect property values, or influence where people choose to live. Model results should be communicated carefully with context about their intended use (targeting help, not blame).\n\n**Self-fulfilling prophecies**: If landlords or lenders learn that certain areas are designated high-risk, they might become more likely to pursue evictions or restrict credit there, creating a self-fulfilling prophecy. Access to model outputs should be controlled.\n\n**Privacy**: While this analysis uses aggregate tract-level data rather than individual records, more granular models could raise privacy concerns. The tradeoff between predictive accuracy and privacy protection should be explicitly considered.\n\n**Displacement of expertise**: Predictive models should complement, not replace, the knowledge of community organizations and tenants themselves. People closest to the problem often understand local conditions better than any statistical model.\n\n**Accountability**: If model predictions are wrong and resources are misallocated, who bears responsibility? Clear governance structures should define how models are used in decision-making and how to appeal decisions influenced by predictions.\n\n## 15.5 Conclusions\n\nOur analysis demonstrates that eviction risk in Philadelphia is predictable enough to support targeted intervention. The concentration of evictions in specific neighborhoods - persistent over time and clustering spatially - creates opportunities for efficient resource deployment. However, prediction alone is not prevention: the model is a tool for guiding action, not a substitute for the policy changes and resource investments needed to address Philadelphia's housing crisis at its roots.\n\nThe most important finding may be the structural nature of eviction patterns. The persistence of hotspots, the racial disparities that cannot be explained by income alone, and the geographic clustering all point to systemic factors - housing discrimination, disinvestment, inadequate tenant protections - that no predictive model can solve. Making evictions predictable is a step toward making them preventable, but ultimately preventing evictions requires addressing the conditions that create them.\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "final_Zhiyuan_Fan_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}