{
  "hash": "b381084b3c90d9b514dc9f300a619560",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Zhiyuan Zhao\"\ndate: 2025/10/02\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:** - Apply spatial operations to answer policy-relevant research questions - Integrate census demographic data with spatial analysis - Create publication-quality visualizations and maps - Work with spatial data from multiple sources - Communicate findings effectively for policy audiences\n\n------------------------------------------------------------------------\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data: - Pennsylvania county boundaries - Pennsylvania hospitals (from lecture data) - Pennsylvania census tracts\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tidycensus)\nlibrary(tigris)\nlibrary(ggplot2)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(units)\nlibrary(patchwork)\nlibrary(ggspatial)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load spatial data\nlibrary(here)\n\npa_counties <- st_read(here::here(\"Assignments\", \"assignment_2\", \"data\", \"Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `/Users/zhaozhiyuan/Documents/GitHub/portfolio-setup-ZhiyuanZhaoMicheal/Assignments/assignment_2/data/Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals   <- st_read(here::here(\"Assignments\", \"assignment_2\", \"data\", \"hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `/Users/zhaozhiyuan/Documents/GitHub/portfolio-setup-ZhiyuanZhaoMicheal/Assignments/assignment_2/data/hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Pennsylvania census tracts\npa_tracts <- tracts(\"PA\", year = 2022, cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |=====================                                                 |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |===============================================================       |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |======================================================================|  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\ncat(\"Number of hospitals:\", nrow(hospitals), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of hospitals: 223 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of census tracts\", nrow(pa_tracts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of census tracts 3445 \n```\n\n\n:::\n\n```{.r .cell-code}\n# CRS info\ncat(\"Counties CRS:\", st_crs(pa_counties)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCounties CRS: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Hospitals CRS:\", st_crs(hospitals)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHospitals CRS: WGS 84 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Census tracts CRS:\", st_crs(pa_tracts)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCensus tracts CRS: NAD83 \n```\n\n\n:::\n:::\n\n\n**Questions to answer:** \n1. How many hospitals are in your dataset? \n223\n2. How many census tracts?\n3445 \n3. What coordinate reference system is each dataset in?\nCounties CRS: WGS 84 / Pseudo-Mercator \nHospitals CRS: WGS 84 \nCensus tracts CRS: NAD83 \n------------------------------------------------------------------------\n\n#### Step 2: Get Demographic Data\n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:** - Total population - Median household income - Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\npa_demo <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = c(\n    total_pop = \"B01003_001\",           \n    median_income = \"B19013_001\",       \n    pop_65_74 = \"B01001_020\",          \n    pop_75_84 = \"B01001_021\",           \n    pop_85p = \"B01001_022\",\n    progress = FALSE         \n  ),\n  year = 2022,\n  geometry = TRUE\n)\n\n# Pivot the data to wide format\npa_demo_wide <- pa_demo %>%\n  select(GEOID, NAME, variable, estimate) %>%\n  pivot_wider(\n    names_from = variable, values_from = estimate,\n    values_fill = 0\n  ) %>%\n  mutate(\n    pop_65p = rowSums(across(c(pop_65_74, pop_75_84, pop_85p)), na.rm = TRUE),\n    elderly_pct = 100 * pop_65p / total_pop\n  )\n\n# Join to tract boundaries\ntracts_with_demo <- pa_demo_wide\n\n# Check for missing data\ncat(\"Missing income data:\", sum(is.na(tracts_with_demo$median_income)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing income data: 63 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"PA Median income: $\", \n    median(tracts_with_demo$median_income, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPA Median income: $ 70188 \n```\n\n\n:::\n:::\n\n\n**Questions to answer:** \n- What year of ACS data are you using? \n2022\n- How many tracts have missing income data?\n63\n- What is the median income across all PA census tracts?\n70188\n\n------------------------------------------------------------------------\n\n#### Step 3: Define Vulnerable Populations\n\nIdentify census tracts with vulnerable populations based on TWO criteria: 1. Low median household income (choose an appropriate threshold) 2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# Define thresholds\nincome_threshold <- 50000   \nelderly_threshold <- 10    \n\n# Identify vulnerable tracts\nvulnerable_tracts <- tracts_with_demo %>%\n  filter(!is.na(median_income)) %>%\n  mutate(\n    low_income = median_income < income_threshold,\n    sign_elderly = elderly_pct > elderly_threshold,\n    vulnerable = low_income | sign_elderly\n  )\n\n# Summaries\nsummary_vals <- list(\n  pa_median = median(tracts_with_demo$median_income, na.rm = TRUE),\n  n_vul = sum(vulnerable_tracts$vulnerable),\n  pct_vul = round(mean(vulnerable_tracts$vulnerable) * 100, 1),\n  n_low = sum(vulnerable_tracts$low_income),\n  n_old = sum(vulnerable_tracts$sign_elderly)\n)\n\ncat(glue::glue(\n  \"Income threshold: ${income_threshold} \\n\",\n  \"Elderly threshold: {elderly_threshold}%\\n\",\n  \"Vulnerable tracts: {summary_vals$n_vul} ({summary_vals$pct_vul}%)\\n\",\n  \"Low median household income: {summary_vals$n_low}\\n\",\n  \"Significant elderly population: {summary_vals$n_old}\\n\"\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIncome threshold: $50000 \nElderly threshold: 10%\nVulnerable tracts: 700 (20.7%)\nLow median household income: 619\nSignificant elderly population: 98\n```\n\n\n:::\n:::\n\n\n**Questions to answer:** \n- What income threshold did you choose and why? \nIncome threshold chosen: $50,000.\nThis represents census tracts where the median household income is below roughly 70% of Pennsylvania’s overall median, marking areas that are relatively economically disadvantaged.\n\n- What elderly population threshold did you choose and why? \nElderly population threshold chosen: 10%.\nTracts where more than 10% of residents are aged 65 or older were considered to have a significant elderly population, a common demographic baseline in vulnerability analyses.\n\n- How many tracts meet your vulnerability criteria? \n700 census tracts meet at least one of the two conditions \n- What percentage of PA census tracts are considered vulnerable by your definition?\n20.7% \n\n------------------------------------------------------------------------\n\n#### Step 4: Calculate Distance to Hospitals\n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n# EPSG 2272 is optimized for southern Pennsylvania counties such as Philadelphia, Lancaster, Chester, and York\ntarget_crs <- 2272\n\n# Reproject all layers\npa_counties_p <- st_transform(pa_counties, target_crs)\nhospitals_p   <- st_transform(hospitals,   target_crs)\nvul_p         <- st_transform(vulnerable_tracts, target_crs)\n\n# Calculate distance from each tract centroid to nearest hospital\n# tract centroids\nvul_centroids <- st_centroid(vul_p)\n\n# nearest hospital index\nnn_idx <- st_nearest_feature(vul_centroids, hospitals_p)\n\n# distance in feet -> miles\ndists_ft <- st_distance(vul_centroids, hospitals_p[nn_idx, ], by_element = TRUE)\ndists_mi <- units::set_units(dists_ft, \"mi\") |> units::drop_units()\n\n# attach results\nvulnerable_tracts_dist <- vul_p |>\n  mutate(\n    nearest_hosp_idx = as.integer(nn_idx),\n    dist_to_hosp_mi  = dists_mi\n  )\n\n# join hospital name if a name field exists\nname_field <- intersect(c(\"NAME\",\"Name\",\"name\",\"HOSP_NAME\",\"HOSPITAL\",\"HospName\"), names(hospitals_p))[1]\nif (!is.na(name_field)) {\n  vulnerable_tracts_dist <- vulnerable_tracts_dist |>\n    mutate(nearest_hosp_name = hospitals_p[[name_field]][nearest_hosp_idx])\n}\n\n# summary statistics\navg_dist <- mean(vulnerable_tracts_dist$dist_to_hosp_mi, na.rm = TRUE)\nmin_dist <- min(vulnerable_tracts_dist$dist_to_hosp_mi, na.rm = TRUE)\nmax_dist <- max(vulnerable_tracts_dist$dist_to_hosp_mi, na.rm = TRUE)\nn_over15 <- sum(vulnerable_tracts_dist$dist_to_hosp_mi > 15, na.rm = TRUE)\n\ncat(\n  \"Average distance to nearest hospital:\", round(avg_dist, 2), \"miles\\n\",\n  \"Minimum distance:\", round(min_dist, 2), \"miles\\n\",\n  \"Maximum distance:\", round(max_dist, 2), \"miles\\n\",\n  \"Number of tracts more than 15 miles from nearest hospital:\", n_over15, \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage distance to nearest hospital: 4.43 miles\n Minimum distance: 0.02 miles\n Maximum distance: 32.84 miles\n Number of tracts more than 15 miles from nearest hospital: 127 \n```\n\n\n:::\n:::\n\n\n**Requirements:** - Use an appropriate projected coordinate system for Pennsylvania - Calculate distances in miles - Explain why you chose your projection\n\n**Questions to answer:** \n- What is the average distance to the nearest hospital for vulnerable tracts? \n4.43 miles\n\n- What is the maximum distance? \n32.84 miles\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n127\n\n------------------------------------------------------------------------\n\n#### Step 5: Identify Underserved Areas\n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n# Definition: vulnerable tracts with distance > 15 miles\n\nvulnerable_tracts_dist <- vulnerable_tracts_dist %>%\n  mutate(underserved = dist_to_hosp_mi > 15)\n\n# Counts and percentages\nn_underserved  <- sum(vulnerable_tracts_dist$underserved, na.rm = TRUE)\nn_with_dist    <- sum(!is.na(vulnerable_tracts_dist$dist_to_hosp_mi))\nn_vulnerable   <- nrow(vulnerable_tracts_dist)\npct_underserved <- round(100 * n_underserved / n_with_dist, 1)\n\ncat(\n  \"Underserved tracts:\", n_underserved, \"\\n\",\n  \"Percent underserved (of tracts with a distance):\", pct_underserved, \"%\\n\",\n  \"Vulnerable tracts total:\", n_vulnerable, \"\\n\",\n  \"With valid distance:\", n_with_dist, \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnderserved tracts: 127 \n Percent underserved (of tracts with a distance): 3.8 %\n Vulnerable tracts total: 3383 \n With valid distance: 3383 \n```\n\n\n:::\n:::\n\n\n**Questions to answer:** \n- How many tracts are underserved? \n127\n\n- What percentage of vulnerable tracts are underserved? \n3.8%\n\n- Does this surprise you? Why or why not?\nYes, a bit less than I expected.\n------------------------------------------------------------------------\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find county name field in pa_counties_p\ncounty_name_field <- intersect(\n  c(\"NAME\",\"NAME20\",\"NAMELSAD\",\"COUNTY\",\"COUNTY_NAM\",\"COUNTYNAME\",\"County\",\"county\",\"NAME10\"),\n  names(pa_counties_p)\n)[1]\n\nif (is.na(county_name_field)) {\n  stop(\"Cannot find a county name field in pa_counties_p. Inspect names(pa_counties_p).\")\n}\n\n# keep only county name + geometry, and rename to COUNTY\ncounties_min <- pa_counties_p %>%\n  dplyr::select(COUNTY = all_of(county_name_field), geometry)\n\n# spatial join tracts -> counties\ntracts_county <- st_join(vulnerable_tracts_dist, counties_min, join = st_intersects, left = FALSE)\n\n# aggregate by COUNTY\ncounty_summary <- tracts_county %>%\n  st_drop_geometry() %>%\n  dplyr::group_by(COUNTY) %>%\n  dplyr::summarise(\n    n_vulnerable        = dplyr::n(),\n    n_underserved       = sum(underserved, na.rm = TRUE),\n    pct_underserved     = round(100 * n_underserved / n_vulnerable, 1),\n    avg_dist_mi         = round(mean(dist_to_hosp_mi, na.rm = TRUE), 2),\n    total_vulnerable_pop= sum(total_pop, na.rm = TRUE)\n  ) %>%\n  dplyr::arrange(dplyr::desc(pct_underserved))\n\n# table + tops\nkable(county_summary, caption = \"County-level Healthcare Accessibility Summary\") %>%\n  kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>County-level Healthcare Accessibility Summary</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> COUNTY </th>\n   <th style=\"text-align:right;\"> n_vulnerable </th>\n   <th style=\"text-align:right;\"> n_underserved </th>\n   <th style=\"text-align:right;\"> pct_underserved </th>\n   <th style=\"text-align:right;\"> avg_dist_mi </th>\n   <th style=\"text-align:right;\"> total_vulnerable_pop </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> JUNIATA </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:right;\"> 60.0 </td>\n   <td style=\"text-align:right;\"> 14.64 </td>\n   <td style=\"text-align:right;\"> 80130 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SULLIVAN </td>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 53.8 </td>\n   <td style=\"text-align:right;\"> 16.75 </td>\n   <td style=\"text-align:right;\"> 39765 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PIKE </td>\n   <td style=\"text-align:right;\"> 36 </td>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 50.0 </td>\n   <td style=\"text-align:right;\"> 16.63 </td>\n   <td style=\"text-align:right;\"> 90387 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SNYDER </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:right;\"> 47.1 </td>\n   <td style=\"text-align:right;\"> 14.14 </td>\n   <td style=\"text-align:right;\"> 76506 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CAMERON </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 45.5 </td>\n   <td style=\"text-align:right;\"> 13.46 </td>\n   <td style=\"text-align:right;\"> 31227 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> POTTER </td>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 40.0 </td>\n   <td style=\"text-align:right;\"> 12.09 </td>\n   <td style=\"text-align:right;\"> 44065 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BRADFORD </td>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:right;\"> 34.8 </td>\n   <td style=\"text-align:right;\"> 12.41 </td>\n   <td style=\"text-align:right;\"> 82113 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLEARFIELD </td>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 31.4 </td>\n   <td style=\"text-align:right;\"> 12.11 </td>\n   <td style=\"text-align:right;\"> 133305 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PERRY </td>\n   <td style=\"text-align:right;\"> 29 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:right;\"> 31.0 </td>\n   <td style=\"text-align:right;\"> 11.24 </td>\n   <td style=\"text-align:right;\"> 136944 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TIOGA </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 29.4 </td>\n   <td style=\"text-align:right;\"> 11.18 </td>\n   <td style=\"text-align:right;\"> 60999 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLINTON </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 25.0 </td>\n   <td style=\"text-align:right;\"> 11.15 </td>\n   <td style=\"text-align:right;\"> 70796 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNION </td>\n   <td style=\"text-align:right;\"> 24 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 25.0 </td>\n   <td style=\"text-align:right;\"> 9.61 </td>\n   <td style=\"text-align:right;\"> 104402 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WYOMING </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 25.0 </td>\n   <td style=\"text-align:right;\"> 12.71 </td>\n   <td style=\"text-align:right;\"> 71055 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ELK </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 21.1 </td>\n   <td style=\"text-align:right;\"> 10.51 </td>\n   <td style=\"text-align:right;\"> 64927 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WAYNE </td>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 20.0 </td>\n   <td style=\"text-align:right;\"> 10.16 </td>\n   <td style=\"text-align:right;\"> 101863 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MONROE </td>\n   <td style=\"text-align:right;\"> 71 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:right;\"> 19.7 </td>\n   <td style=\"text-align:right;\"> 10.32 </td>\n   <td style=\"text-align:right;\"> 239844 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MIFFLIN </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 19.2 </td>\n   <td style=\"text-align:right;\"> 8.72 </td>\n   <td style=\"text-align:right;\"> 86713 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SUSQUEHANNA </td>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 19.0 </td>\n   <td style=\"text-align:right;\"> 10.20 </td>\n   <td style=\"text-align:right;\"> 69376 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FULTON </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 18.2 </td>\n   <td style=\"text-align:right;\"> 11.78 </td>\n   <td style=\"text-align:right;\"> 45546 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FOREST </td>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 16.7 </td>\n   <td style=\"text-align:right;\"> 11.67 </td>\n   <td style=\"text-align:right;\"> 32266 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MCKEAN </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 15.8 </td>\n   <td style=\"text-align:right;\"> 8.82 </td>\n   <td style=\"text-align:right;\"> 54243 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CENTRE </td>\n   <td style=\"text-align:right;\"> 53 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 13.2 </td>\n   <td style=\"text-align:right;\"> 7.77 </td>\n   <td style=\"text-align:right;\"> 205338 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NORTHUMBERLAND </td>\n   <td style=\"text-align:right;\"> 39 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 12.8 </td>\n   <td style=\"text-align:right;\"> 10.05 </td>\n   <td style=\"text-align:right;\"> 157577 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHESTER </td>\n   <td style=\"text-align:right;\"> 157 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 12.7 </td>\n   <td style=\"text-align:right;\"> 6.65 </td>\n   <td style=\"text-align:right;\"> 680335 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLARION </td>\n   <td style=\"text-align:right;\"> 25 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 12.0 </td>\n   <td style=\"text-align:right;\"> 9.22 </td>\n   <td style=\"text-align:right;\"> 83316 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DAUPHIN </td>\n   <td style=\"text-align:right;\"> 83 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 12.0 </td>\n   <td style=\"text-align:right;\"> 5.60 </td>\n   <td style=\"text-align:right;\"> 358417 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CRAWFORD </td>\n   <td style=\"text-align:right;\"> 37 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 10.8 </td>\n   <td style=\"text-align:right;\"> 8.42 </td>\n   <td style=\"text-align:right;\"> 135400 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HUNTINGDON </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 10.7 </td>\n   <td style=\"text-align:right;\"> 9.37 </td>\n   <td style=\"text-align:right;\"> 103995 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SCHUYLKILL </td>\n   <td style=\"text-align:right;\"> 62 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 9.7 </td>\n   <td style=\"text-align:right;\"> 7.48 </td>\n   <td style=\"text-align:right;\"> 222698 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LANCASTER </td>\n   <td style=\"text-align:right;\"> 136 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:right;\"> 8.8 </td>\n   <td style=\"text-align:right;\"> 5.98 </td>\n   <td style=\"text-align:right;\"> 641211 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LYCOMING </td>\n   <td style=\"text-align:right;\"> 47 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 8.5 </td>\n   <td style=\"text-align:right;\"> 6.26 </td>\n   <td style=\"text-align:right;\"> 173737 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WARREN </td>\n   <td style=\"text-align:right;\"> 24 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 8.3 </td>\n   <td style=\"text-align:right;\"> 6.84 </td>\n   <td style=\"text-align:right;\"> 80752 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> JEFFERSON </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 7.7 </td>\n   <td style=\"text-align:right;\"> 7.56 </td>\n   <td style=\"text-align:right;\"> 94634 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SOMERSET </td>\n   <td style=\"text-align:right;\"> 39 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 7.7 </td>\n   <td style=\"text-align:right;\"> 7.43 </td>\n   <td style=\"text-align:right;\"> 138787 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ERIE </td>\n   <td style=\"text-align:right;\"> 77 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 6.5 </td>\n   <td style=\"text-align:right;\"> 5.59 </td>\n   <td style=\"text-align:right;\"> 292643 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FRANKLIN </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 6.5 </td>\n   <td style=\"text-align:right;\"> 5.94 </td>\n   <td style=\"text-align:right;\"> 212297 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> VENANGO </td>\n   <td style=\"text-align:right;\"> 33 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 6.1 </td>\n   <td style=\"text-align:right;\"> 8.34 </td>\n   <td style=\"text-align:right;\"> 102067 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CARBON </td>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 5.7 </td>\n   <td style=\"text-align:right;\"> 7.34 </td>\n   <td style=\"text-align:right;\"> 134867 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ARMSTRONG </td>\n   <td style=\"text-align:right;\"> 39 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 5.1 </td>\n   <td style=\"text-align:right;\"> 8.49 </td>\n   <td style=\"text-align:right;\"> 137004 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BEDFORD </td>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 4.3 </td>\n   <td style=\"text-align:right;\"> 8.73 </td>\n   <td style=\"text-align:right;\"> 93406 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CUMBERLAND </td>\n   <td style=\"text-align:right;\"> 80 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 3.8 </td>\n   <td style=\"text-align:right;\"> 5.90 </td>\n   <td style=\"text-align:right;\"> 370539 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FAYETTE </td>\n   <td style=\"text-align:right;\"> 59 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 3.4 </td>\n   <td style=\"text-align:right;\"> 6.56 </td>\n   <td style=\"text-align:right;\"> 191334 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LUZERNE </td>\n   <td style=\"text-align:right;\"> 119 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 3.4 </td>\n   <td style=\"text-align:right;\"> 5.16 </td>\n   <td style=\"text-align:right;\"> 388640 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> COLUMBIA </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 3.3 </td>\n   <td style=\"text-align:right;\"> 6.45 </td>\n   <td style=\"text-align:right;\"> 120618 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> YORK </td>\n   <td style=\"text-align:right;\"> 135 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 3.0 </td>\n   <td style=\"text-align:right;\"> 5.24 </td>\n   <td style=\"text-align:right;\"> 568950 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LACKAWANNA </td>\n   <td style=\"text-align:right;\"> 76 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 2.6 </td>\n   <td style=\"text-align:right;\"> 3.88 </td>\n   <td style=\"text-align:right;\"> 270270 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> INDIANA </td>\n   <td style=\"text-align:right;\"> 40 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2.5 </td>\n   <td style=\"text-align:right;\"> 7.07 </td>\n   <td style=\"text-align:right;\"> 142235 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ADAMS </td>\n   <td style=\"text-align:right;\"> 45 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2.2 </td>\n   <td style=\"text-align:right;\"> 6.34 </td>\n   <td style=\"text-align:right;\"> 185064 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LEBANON </td>\n   <td style=\"text-align:right;\"> 47 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2.1 </td>\n   <td style=\"text-align:right;\"> 5.33 </td>\n   <td style=\"text-align:right;\"> 203190 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BUTLER </td>\n   <td style=\"text-align:right;\"> 65 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 1.5 </td>\n   <td style=\"text-align:right;\"> 5.96 </td>\n   <td style=\"text-align:right;\"> 269083 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ALLEGHENY </td>\n   <td style=\"text-align:right;\"> 419 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2.49 </td>\n   <td style=\"text-align:right;\"> 1375774 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BEAVER </td>\n   <td style=\"text-align:right;\"> 72 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 5.20 </td>\n   <td style=\"text-align:right;\"> 240367 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BERKS </td>\n   <td style=\"text-align:right;\"> 130 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 4.61 </td>\n   <td style=\"text-align:right;\"> 543881 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BLAIR </td>\n   <td style=\"text-align:right;\"> 53 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 4.99 </td>\n   <td style=\"text-align:right;\"> 181183 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BUCKS </td>\n   <td style=\"text-align:right;\"> 181 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 3.66 </td>\n   <td style=\"text-align:right;\"> 801951 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CAMBRIA </td>\n   <td style=\"text-align:right;\"> 59 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 6.03 </td>\n   <td style=\"text-align:right;\"> 195090 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DELAWARE </td>\n   <td style=\"text-align:right;\"> 172 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2.33 </td>\n   <td style=\"text-align:right;\"> 671006 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GREENE </td>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 8.41 </td>\n   <td style=\"text-align:right;\"> 66760 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LAWRENCE </td>\n   <td style=\"text-align:right;\"> 37 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 6.04 </td>\n   <td style=\"text-align:right;\"> 129315 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LEHIGH </td>\n   <td style=\"text-align:right;\"> 108 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 3.31 </td>\n   <td style=\"text-align:right;\"> 482921 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MERCER </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 4.81 </td>\n   <td style=\"text-align:right;\"> 140781 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MONTGOMERY </td>\n   <td style=\"text-align:right;\"> 300 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2.49 </td>\n   <td style=\"text-align:right;\"> 1218103 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MONTOUR </td>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 5.14 </td>\n   <td style=\"text-align:right;\"> 67844 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NORTHAMPTON </td>\n   <td style=\"text-align:right;\"> 94 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 4.29 </td>\n   <td style=\"text-align:right;\"> 394848 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PHILADELPHIA </td>\n   <td style=\"text-align:right;\"> 422 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 1.13 </td>\n   <td style=\"text-align:right;\"> 1746810 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WASHINGTON </td>\n   <td style=\"text-align:right;\"> 84 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 4.67 </td>\n   <td style=\"text-align:right;\"> 308585 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WESTMORELAND </td>\n   <td style=\"text-align:right;\"> 156 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 4.63 </td>\n   <td style=\"text-align:right;\"> 507125 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\ntop5_pct <- county_summary %>%\n  dplyr::slice_max(pct_underserved, n = 5) %>%\n  dplyr::select(COUNTY, pct_underserved)\n\ntop5_pop <- county_summary %>%\n  dplyr::slice_max(total_vulnerable_pop, n = 5) %>%\n  dplyr::select(COUNTY, total_vulnerable_pop)\n\ncat(\"Top 5 counties by % underserved:\\n\"); print(top5_pct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 5 counties by % underserved:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  COUNTY   pct_underserved\n  <chr>              <dbl>\n1 JUNIATA             60  \n2 SULLIVAN            53.8\n3 PIKE                50  \n4 SNYDER              47.1\n5 CAMERON             45.5\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nTop 5 counties by total vulnerable population:\\n\"); print(top5_pop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTop 5 counties by total vulnerable population:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  COUNTY       total_vulnerable_pop\n  <chr>                       <dbl>\n1 PHILADELPHIA              1746810\n2 ALLEGHENY                 1375774\n3 MONTGOMERY                1218103\n4 BUCKS                      801951\n5 CHESTER                    680335\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:** - Number of vulnerable tracts - Number of underserved tracts\\\n- Percentage of vulnerable tracts that are underserved - Average distance to nearest hospital for vulnerable tracts - Total vulnerable population\n\n**Questions to answer:** \n- Which 5 counties have the highest percentage of underserved vulnerable tracts? \nJUNIATA, SULLIVAN, PIKE, SNYDER, CAMERON\n\n- Which counties have the most vulnerable people living far from hospitals? \nPHILADELPHIA, ALLEGHENY, MONTGOMERY, BUCKS, CHESTER\n\n- Are there any patterns in where underserved counties are located?\nYes. Underserved counties show clear geographic patterns:\n\t•\tSpatial distribution: They are concentrated in rural, mountainous, and sparsely populated regions of Pennsylvania—especially in central and northern counties such as Juniata, Cameron, Sullivan, and Pike.\n\t•\tInfrastructure gap: These areas have low hospital density and limited transportation access, leading to longer travel times to medical facilities.\n\t•\tUrban contrast: Southeastern and southwestern metropolitan areas (Philadelphia, Allegheny, Montgomery, Bucks, Chester) have good hospital coverage and almost no tracts beyond 15 miles.\n\n------------------------------------------------------------------------\n\n#### Step 7: Create Summary Table\n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n# Priority rule: sort by % underserved (desc), then avg distance (desc),\n# then # underserved tracts (desc), then vulnerable population (desc)\n\npriority_tbl <- county_summary %>%\n  arrange(desc(pct_underserved), desc(avg_dist_mi), desc(n_underserved), desc(total_vulnerable_pop)) %>%\n  slice_head(n = 10) %>%\n  transmute(\n    County = COUNTY,\n    `Vulnerable tracts`   = scales::comma(n_vulnerable),\n    `Underserved tracts`  = scales::comma(n_underserved),\n    `% underserved`       = scales::number(pct_underserved, accuracy = 0.1),\n    `Avg distance (mi)`   = scales::number(avg_dist_mi, accuracy = 0.01),\n    `Vulnerable population` = scales::comma(total_vulnerable_pop)\n  )\n\nkable(\n  priority_tbl,\n  caption = \"Top 10 Priority Counties for Healthcare Investment (sorted by % underserved, distance, underserved count, population)\"\n) %>%\n  kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Top 10 Priority Counties for Healthcare Investment (sorted by % underserved, distance, underserved count, population)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> County </th>\n   <th style=\"text-align:left;\"> Vulnerable tracts </th>\n   <th style=\"text-align:left;\"> Underserved tracts </th>\n   <th style=\"text-align:left;\"> % underserved </th>\n   <th style=\"text-align:left;\"> Avg distance (mi) </th>\n   <th style=\"text-align:left;\"> Vulnerable population </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> JUNIATA </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:left;\"> 60.0 </td>\n   <td style=\"text-align:left;\"> 14.64 </td>\n   <td style=\"text-align:left;\"> 80,130 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SULLIVAN </td>\n   <td style=\"text-align:left;\"> 13 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:left;\"> 53.8 </td>\n   <td style=\"text-align:left;\"> 16.75 </td>\n   <td style=\"text-align:left;\"> 39,765 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PIKE </td>\n   <td style=\"text-align:left;\"> 36 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:left;\"> 50.0 </td>\n   <td style=\"text-align:left;\"> 16.63 </td>\n   <td style=\"text-align:left;\"> 90,387 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SNYDER </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:left;\"> 47.1 </td>\n   <td style=\"text-align:left;\"> 14.14 </td>\n   <td style=\"text-align:left;\"> 76,506 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CAMERON </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 45.5 </td>\n   <td style=\"text-align:left;\"> 13.46 </td>\n   <td style=\"text-align:left;\"> 31,227 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> POTTER </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 40.0 </td>\n   <td style=\"text-align:left;\"> 12.09 </td>\n   <td style=\"text-align:left;\"> 44,065 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BRADFORD </td>\n   <td style=\"text-align:left;\"> 23 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:left;\"> 34.8 </td>\n   <td style=\"text-align:left;\"> 12.41 </td>\n   <td style=\"text-align:left;\"> 82,113 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLEARFIELD </td>\n   <td style=\"text-align:left;\"> 35 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:left;\"> 31.4 </td>\n   <td style=\"text-align:left;\"> 12.11 </td>\n   <td style=\"text-align:left;\"> 133,305 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PERRY </td>\n   <td style=\"text-align:left;\"> 29 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:left;\"> 31.0 </td>\n   <td style=\"text-align:left;\"> 11.24 </td>\n   <td style=\"text-align:left;\"> 136,944 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TIOGA </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 29.4 </td>\n   <td style=\"text-align:left;\"> 11.18 </td>\n   <td style=\"text-align:left;\"> 60,999 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Requirements:** - Use `knitr::kable()` or similar for formatting - Include descriptive column names - Format numbers appropriately (commas for population, percentages, etc.) - Add an informative caption - Sort by priority (you decide the metric)\n\n------------------------------------------------------------------------\n\n## Part 2: Comprehensive Visualization\n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth\n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(dplyr)\n\n# join county-level stats to county geometries\ncounties_map <- pa_counties_p %>%\n  left_join(county_summary, by = c(\"COUNTY_NAM\" = \"COUNTY\"))\n\n# choropleth filled by % underserved; hospitals as points\nggplot() +\n  geom_sf(data = counties_map, aes(fill = pct_underserved), color = NA) +\n  geom_sf(data = hospitals_p, size = 0.6, alpha = 0.7) +\n  scale_fill_viridis_c(\n    name = \"% underserved tracts\",\n    labels = label_percent(accuracy = 0.1, scale = 1),\n    na.value = \"grey90\"\n  ) +\n  labs(\n    title = \"Healthcare Access Gaps by County in Pennsylvania\",\n    subtitle = \"% of vulnerable tracts > 15 miles from nearest hospital\",\n    caption = \"Sources: ACS 2022 (tidycensus), PA hospitals, county boundaries\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Zhiyuan_Zhao_assignment2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Requirements:** - Fill counties by percentage of vulnerable tracts that are underserved - Include hospital locations as points - Use an appropriate color scheme - Include clear title, subtitle, and caption - Use `theme_void()` or similar clean theme - Add a legend with formatted labels\n\n------------------------------------------------------------------------\n\n### Map 2: Detailed Vulnerability Map\n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n# Data prep\ntracts_map <- vulnerable_tracts_dist\nunderserved_tracts <- tracts_map %>% filter(underserved)\n\nggplot() +\n  # context: county boundaries\n  geom_sf(data = pa_counties_p, fill = NA, color = \"grey50\", linewidth = 0.2) +\n  # all vulnerable tracts (muted)\n  geom_sf(data = tracts_map, fill = \"grey85\", color = NA, alpha = 0.6) +\n  # underserved vulnerable tracts (highlight)\n  geom_sf(data = underserved_tracts, aes(fill = dist_to_hosp_mi), color = NA) +\n  # hospitals\n  geom_sf(data = hospitals_p, shape = 21, fill = \"black\", color = \"white\", size = 1) +\n  scale_fill_viridis_c(\n    name = \"Distance to hospital (mi)\",\n    option = \"C\",\n    limits = c(15, max(underserved_tracts$dist_to_hosp_mi, na.rm = TRUE)),\n    oob = scales::squish\n  ) +\n  labs(\n    title = \"Underserved Vulnerable Tracts in Pennsylvania\",\n    subtitle = \"Tracts with vulnerable populations located > 15 miles from the nearest hospital\",\n    caption = \"Sources: ACS 2022 (tidycensus), PA hospitals, county boundaries\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Zhiyuan_Zhao_assignment2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**Requirements:** - Show underserved vulnerable tracts in a contrasting color - Include county boundaries for context - Show hospital locations - Use appropriate visual hierarchy (what should stand out?) - Include informative title and subtitle\n\n------------------------------------------------------------------------\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n# Histogram of distances (vulnerable tracts)\np_hist <- ggplot(vulnerable_tracts_dist, aes(x = dist_to_hosp_mi)) +\n  geom_histogram(bins = 40) +\n  geom_vline(xintercept = 15, linetype = \"dashed\") +\n  labs(\n    title = \"Distance to Nearest Hospital (Vulnerable Tracts)\",\n    x = \"Distance (miles)\", y = \"Count\",\n    caption = \"Dashed line at 15 miles threshold\"\n  ) +\n  theme_minimal()\n\n# Top-10 counties by underserved tracts (requires county_summary from Step 6)\ntop10_underserved <- county_summary %>%\n  slice_max(n_underserved, n = 10) %>%\n  mutate(COUNTY = reorder(COUNTY, n_underserved))\n\np_bar <- ggplot(top10_underserved, aes(x = COUNTY, y = n_underserved)) +\n  geom_col() +\n  coord_flip() +\n  labs(\n    title = \"Top 10 Counties by Number of Underserved Tracts\",\n    x = NULL, y = \"Underserved tracts (count)\"\n  ) +\n  theme_minimal()\n\n# Scatter: distance vs. population, highlighting underserved tracts\np_scatter <- ggplot(vulnerable_tracts_dist,\n                    aes(x = total_pop, y = dist_to_hosp_mi, alpha = underserved)) +\n  geom_point() +\n  scale_x_continuous(labels = comma) +\n  scale_alpha_manual(values = c(`TRUE` = 1, `FALSE` = 0.3), guide = \"none\") +\n  labs(\n    title = \"Distance vs. Tract Population (Vulnerable Tracts)\",\n    x = \"Tract total population\", y = \"Distance to nearest hospital (miles)\"\n  ) +\n  theme_minimal()\n\n# Display\n(p_hist | p_scatter) / p_bar\n```\n\n::: {.cell-output-display}\n![](Zhiyuan_Zhao_assignment2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Brief interpretation\ncat(\"Interpretation:\",\n    \"Most vulnerable tracts lie within 15 miles, but a right tail exceeds the threshold.\",\n    \"Underserved tracts concentrate in a small set of counties.\",\n    \"Higher-population tracts are not necessarily farther from hospitals; gaps are mainly geographic.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretation: Most vulnerable tracts lie within 15 miles, but a right tail exceeds the threshold. Underserved tracts concentrate in a small set of counties. Higher-population tracts are not necessarily farther from hospitals; gaps are mainly geographic.\n```\n\n\n:::\n:::\n\n\n**Suggested chart types:** - Histogram or density plot of distances - Box plot comparing distances across regions - Bar chart of underserved tracts by county - Scatter plot of distance vs. vulnerable population size\n\n**Requirements:** - Clear axes labels with units - Appropriate title - Professional formatting - Brief interpretation (1-2 sentences as a caption or in text)\n\n------------------------------------------------------------------------\n\n## Part 3: Bring Your Own Data Analysis\n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Your Analysis\n\n**Your Task:**\n\n1.  **Find and load additional data**\n    -   Document your data source\n    -   Check and standardize the CRS\n    -   Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Config\ncrs_proj <- 2272          # Pennsylvania South State Plane (US feet)\nbuf_ft   <- 2640          # 0.5 mile ≈ 2640 ft\n\n# Load schools \nschools <- st_read(here(\"Assignments\", \"assignment_2\", \"data\",\"Schools.geojson\"), quiet = TRUE) %>%\n  st_transform(crs_proj)\n\n# Get Philadelphia tracts with children population (ACS 2022)\n# B09001_001 = total population under 18\nacs_children <- get_acs(\n  geography = \"tract\",\n  variables = \"B09001_001\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2022,\n  geometry = TRUE\n) %>%\n  st_transform(crs_proj) %>%\n  rename(child_pop = estimate) %>%\n  select(GEOID, NAME, child_pop, geometry) %>%\n  mutate(\n    tract_name = str_replace(NAME, \", Philadelphia County, Pennsylvania\", \"\")\n  )\n\n# Build Philadelphia boundary from tracts\nphila_boundary <- acs_children %>% st_union() %>% st_as_sf()\n\n# Data overview\ncat(\"\\n===== DATA OVERVIEW =====\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===== DATA OVERVIEW =====\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n-- Schools --\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n-- Schools --\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 495 features and 14 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 2664437 ymin: 219220.7 xmax: 2745960 ymax: 301940.8\nProjected CRS: NAD83 / Pennsylvania South (ftUS)\nFirst 10 features:\n         aun school_num location_id                    school_name\n1  226518902         NA        <NA> ST MARYS INTERPAROCHIAL SCHOOL\n2  226518722         NA        <NA>               ST MARTHA SCHOOL\n3  226514052         NA        <NA>           MATERNITY BVM SCHOOL\n4  226514852         NA        <NA>     OUR LADY OF CALVARY SCHOOL\n5  226511102         NA        <NA>         CHRIST THE KING SCHOOL\n6  300511820         NA        <NA>     BEGINNINGS LEARNING CENTER\n7  226511232         NA        <NA>                 JUBILEE SCHOOL\n8  226514112         NA        <NA>              MILL CREEK SCHOOL\n9  226512252         NA        <NA>          HOLY INNOCENTS SCHOOL\n10 226510064         NA        <NA>  SPRING GARDEN ACADEMY - TIOGA\n                school_name_label         street_address zip_code\n1  ST MARYS INTERPAROCHIAL SCHOOL          440 LOCUST ST    19106\n2                ST MARTHA SCHOOL       11321 ACADEMY RD    19154\n3            MATERNITY BVM SCHOOL 9322 OLD BUSTLETON AVE    19115\n4      OUR LADY OF CALVARY SCHOOL       11023 KIPLING LN    19154\n5          CHRIST THE KING SCHOOL   3205 CHESTERFIELD RD    19114\n6      BEGINNINGS LEARNING CENTER          620 S 10TH ST    19147\n7                  JUBILEE SCHOOL       4211 CHESTER AVE    19104\n8               MILL CREEK SCHOOL         4601 MARKET ST    19139\n9  HOLY INNOCENTS CATHOLIC SCHOOL      1312 E BRISTOL ST    19124\n10     SPRING GARDEN ACAD - TIOGA      3501-05 N 17TH ST    19140\n     phone_number        grade_level grade_org enrollment type type_specific\n1  (215) 923-7522  ELEMENTARY/MIDDLE       K-8         NA    3   ARCHDIOCESE\n2  (215) 632-0320  ELEMENTARY/MIDDLE    PREK-8         NA    3   ARCHDIOCESE\n3  (215) 673-0235  ELEMENTARY/MIDDLE    PREK-8         NA    3   ARCHDIOCESE\n4  (215) 637-1648  ELEMENTARY/MIDDLE    PREK-8         NA    3   ARCHDIOCESE\n5  (215) 632-1375  ELEMENTARY/MIDDLE    PREK-8         NA    3   ARCHDIOCESE\n6  (215) 627-3668 PRE-K/KINDERGARTEN    PREK-K         NA    3       PRIVATE\n7  (215) 387-7592  ELEMENTARY SCHOOL    PREK-6         NA    3       PRIVATE\n8  (215) 471-4900        MIDDLE/HIGH      7-12         NA    3       PRIVATE\n9  (215) 743-5909  ELEMENTARY/MIDDLE    PREK-8         NA    3   ARCHDIOCESE\n10 (215) 226-1000  ELEMENTARY/MIDDLE    PREK-8         NA    3       PRIVATE\n   objectid                 geometry\n1         1 POINT (2697499 233938.6)\n2         2 POINT (2742004 286870.6)\n3         3 POINT (2726981 284343.6)\n4         4 POINT (2743816 283938.8)\n5         5   POINT (2739277 282304)\n6         6   POINT (2694931 232466)\n7         7 POINT (2681044 234468.1)\n8         8   POINT (2679114 238320)\n9         9 POINT (2710441 258368.2)\n10       10 POINT (2694962 256058.9)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCRS:\\n\"); print(st_crs(schools))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:2272 \n  wkt:\nPROJCRS[\"NAD83 / Pennsylvania South (ftUS)\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"SPCS83 Pennsylvania South zone (US survey foot)\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",39.3333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-77.75,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",40.9666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",39.9333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1968500,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",0,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"United States (USA) - Pennsylvania - counties of Adams; Allegheny; Armstrong; Beaver; Bedford; Berks; Blair; Bucks; Butler; Cambria; Chester; Cumberland; Dauphin; Delaware; Fayette; Franklin; Fulton; Greene; Huntingdon; Indiana; Juniata; Lancaster; Lawrence; Lebanon; Lehigh; Mifflin; Montgomery; Northampton; Perry; Philadelphia; Schuylkill; Snyder; Somerset; Washington; Westmoreland; York.\"],\n        BBOX[39.71,-80.53,41.18,-74.72]],\n    ID[\"EPSG\",2272]]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nField summary:\\n\"); glimpse(schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nField summary:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 495\nColumns: 15\n$ aun               <int> 226518902, 226518722, 226514052, 226514852, 22651110…\n$ school_num        <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ location_id       <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ school_name       <chr> \"ST MARYS INTERPAROCHIAL SCHOOL\", \"ST MARTHA SCHOOL\"…\n$ school_name_label <chr> \"ST MARYS INTERPAROCHIAL SCHOOL\", \"ST MARTHA SCHOOL\"…\n$ street_address    <chr> \"440 LOCUST ST\", \"11321 ACADEMY RD\", \"9322 OLD BUSTL…\n$ zip_code          <chr> \"19106\", \"19154\", \"19115\", \"19154\", \"19114\", \"19147\"…\n$ phone_number      <chr> \"(215) 923-7522\", \"(215) 632-0320\", \"(215) 673-0235\"…\n$ grade_level       <chr> \"ELEMENTARY/MIDDLE\", \"ELEMENTARY/MIDDLE\", \"ELEMENTAR…\n$ grade_org         <chr> \"K-8\", \"PREK-8\", \"PREK-8\", \"PREK-8\", \"PREK-8\", \"PREK…\n$ enrollment        <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ type              <int> 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1…\n$ type_specific     <chr> \"ARCHDIOCESE\", \"ARCHDIOCESE\", \"ARCHDIOCESE\", \"ARCHDI…\n$ objectid          <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1…\n$ geometry          <POINT [US_survey_foot]> POINT (2697499 233938.6), POINT (…\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCoordinate summary:\\n\"); print(summary(st_coordinates(schools)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCoordinate summary:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       X                 Y         \n Min.   :2664437   Min.   :219221  \n 1st Qu.:2687329   1st Qu.:240118  \n Median :2694639   Median :251800  \n Mean   :2697454   Mean   :253321  \n 3rd Qu.:2704980   3rd Qu.:266685  \n Max.   :2745960   Max.   :301941  \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n-- Philadelphia tracts (ACS 2022) --\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n-- Philadelphia tracts (ACS 2022) --\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(acs_children)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 408 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2660586 ymin: 204667.4 xmax: 2750104 ymax: 304965.3\nProjected CRS: NAD83 / Pennsylvania South (ftUS)\nFirst 10 features:\n         GEOID                                                  NAME child_pop\n1  42101001500    Census Tract 15; Philadelphia County; Pennsylvania       563\n2  42101001800    Census Tract 18; Philadelphia County; Pennsylvania       471\n3  42101002802 Census Tract 28.02; Philadelphia County; Pennsylvania       806\n4  42101004001 Census Tract 40.01; Philadelphia County; Pennsylvania       574\n5  42101006300    Census Tract 63; Philadelphia County; Pennsylvania      1226\n6  42101007700    Census Tract 77; Philadelphia County; Pennsylvania       102\n7  42101008701 Census Tract 87.01; Philadelphia County; Pennsylvania       427\n8  42101011000   Census Tract 110; Philadelphia County; Pennsylvania       808\n9  42101011500   Census Tract 115; Philadelphia County; Pennsylvania      1138\n10 42101014000   Census Tract 140; Philadelphia County; Pennsylvania       965\n                         geometry\n1  MULTIPOLYGON (((2693050 232...\n2  MULTIPOLYGON (((2692904 231...\n3  MULTIPOLYGON (((2692735 226...\n4  MULTIPOLYGON (((2692022 225...\n5  MULTIPOLYGON (((2670526 223...\n6  MULTIPOLYGON (((2679724 234...\n7  MULTIPOLYGON (((2679769 234...\n8  MULTIPOLYGON (((2679270 244...\n9  MULTIPOLYGON (((2667375 244...\n10 MULTIPOLYGON (((2692273 243...\n                                              tract_name\n1     Census Tract 15; Philadelphia County; Pennsylvania\n2     Census Tract 18; Philadelphia County; Pennsylvania\n3  Census Tract 28.02; Philadelphia County; Pennsylvania\n4  Census Tract 40.01; Philadelphia County; Pennsylvania\n5     Census Tract 63; Philadelphia County; Pennsylvania\n6     Census Tract 77; Philadelphia County; Pennsylvania\n7  Census Tract 87.01; Philadelphia County; Pennsylvania\n8    Census Tract 110; Philadelphia County; Pennsylvania\n9    Census Tract 115; Philadelphia County; Pennsylvania\n10   Census Tract 140; Philadelphia County; Pennsylvania\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCRS:\\n\"); print(st_crs(acs_children))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:2272 \n  wkt:\nPROJCRS[\"NAD83 / Pennsylvania South (ftUS)\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"SPCS83 Pennsylvania South zone (US survey foot)\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",39.3333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-77.75,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",40.9666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",39.9333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1968500,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",0,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"United States (USA) - Pennsylvania - counties of Adams; Allegheny; Armstrong; Beaver; Bedford; Berks; Blair; Bucks; Butler; Cambria; Chester; Cumberland; Dauphin; Delaware; Fayette; Franklin; Fulton; Greene; Huntingdon; Indiana; Juniata; Lancaster; Lawrence; Lebanon; Lehigh; Mifflin; Montgomery; Northampton; Perry; Philadelphia; Schuylkill; Snyder; Somerset; Washington; Westmoreland; York.\"],\n        BBOX[39.71,-80.53,41.18,-74.72]],\n    ID[\"EPSG\",2272]]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nChild population summary:\\n\"); print(summary(acs_children$child_pop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nChild population summary:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0   368.5   744.5   839.7  1142.0  3894.0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Quick visualization check\nggplot() +\n  geom_sf(data = acs_children, fill = \"grey95\", color = NA) +\n  geom_sf(data = schools, color = \"blue\", size = 0.6) +\n  labs(title = \"Spatial extent check – Schools and Philadelphia tracts\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Zhiyuan_Zhao_assignment2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why? \nPhiladelphia public schools and 2022 ACS census tracts with children population (under 18 years old). The school dataset defines the physical locations of educational facilities, while the tract-level ACS data provides demographic context to measure how many children live within and outside the school service areas.\n\n- What is the data source and date? - How many features does it contain? \nThe school locations were downloaded from OpenDataPhilly (“Philadelphia Schools”).\nThe children population data were retrieved from the U.S. Census Bureau’s American Community Survey (ACS) 5-Year Estimates, 2022 release via the tidycensus R package.\nThe OpenDataPhilly schools layer contains about 300 school points within Philadelphia.\nThe ACS dataset includes 384 census tracts for the City of Philadelphia, each with a child_pop attribute (population under 18).\n\n- What CRS is it in? Did you need to transform it?\nBoth datasets were standardized to EPSG:2272 — Pennsylvania South State Plane (US feet) to ensure accurate distance and area calculations.\nThe original school data used a geographic coordinate system (latitude/longitude), so it was transformed to EPSG:2272 before creating 0.5-mile buffers. The ACS data were downloaded with geometry and then also projected to EPSG:2272 for consistency.\n\n\n------------------------------------------------------------------------\n\n2.  **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Examples:** - \"Do vulnerable tracts have adequate public transit access to hospitals?\" - \"Are EMS stations appropriately located near vulnerable populations?\" - \"Do areas with low vehicle access have worse hospital access?\"\n\nDo areas in Philadelphia with higher concentrations of children have adequate spatial access to schools within a 0.5-mile walking distance?\n------------------------------------------------------------------------\n\n3.  **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):** - Buffers - Spatial joins - Spatial filtering with predicates - Distance calculations - Intersections or unions - Point-in-polygon aggregation\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n# Build 0.5-mile service buffer of schools\nschool_buf <- schools %>%\n  st_buffer(buf_ft) %>%      # service area\n  st_union() %>%             # dissolve overlaps\n  st_as_sf()\n\n# Tract-level coverage and areal-weighted children counts\narea_total   <- st_area(acs_children)\noverlap_idx  <- st_intersects(acs_children, school_buf)\nhas_overlap  <- lengths(overlap_idx) > 0\narea_covered <- units::set_units(0, \"ft^2\")\narea_covered[has_overlap] <- st_area(st_intersection(acs_children[has_overlap, ], school_buf))\n\ntracts_cov <- acs_children %>%\n  mutate(\n    area_total   = area_total,\n    area_covered = area_covered,\n    pct_covered  = pmin(1, as.numeric(area_covered / area_total)),\n    children_in_service = child_pop * pct_covered,\n    children_in_gap     = child_pop * (1 - pct_covered),\n    access_flag = case_when(\n      pct_covered >= 0.90 ~ \"Well covered (≥90%)\",\n      pct_covered >= 0.50 ~ \"Partially covered (50–90%)\",\n      TRUE               ~ \"Gap (<50%)\"\n    )\n  )\n\n\n# Citywide summaries\ncity_summary <- tracts_cov %>%\n  st_drop_geometry() %>%\n  summarise(\n    tracts              = n(),\n    children_total      = sum(child_pop, na.rm = TRUE),\n    children_served     = sum(children_in_service, na.rm = TRUE),\n    children_gap        = sum(children_in_gap, na.rm = TRUE),\n    pct_children_served = round(100 * children_served / children_total, 1),\n    pct_children_gap    = round(100 * children_gap / children_total, 1)\n  )\ncat(\"\\n===== CITYWIDE SUMMARY =====\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===== CITYWIDE SUMMARY =====\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(city_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  tracts children_total children_served children_gap pct_children_served\n1    408         342585        325716.3     16354.73                95.1\n  pct_children_gap\n1              4.8\n```\n\n\n:::\n\n```{.r .cell-code}\nband_summary <- tracts_cov %>%\n  st_drop_geometry() %>%\n  group_by(access_flag) %>%\n  summarise(\n    n_tracts     = n(),\n    children_sum = sum(child_pop, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(match(access_flag, c(\"Well covered (≥90%)\",\"Partially covered (50–90%)\",\"Gap (<50%)\")))\ncat(\"\\n===== COVERAGE BANDS =====\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===== COVERAGE BANDS =====\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(band_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  access_flag                n_tracts children_sum\n  <chr>                         <int>        <dbl>\n1 Well covered (≥90%)             322       293209\n2 Partially covered (50–90%)       57        41085\n3 Gap (<50%)                       29         8291\n```\n\n\n:::\n\n```{.r .cell-code}\ntop_gap_tracts <- tracts_cov %>%\n  st_drop_geometry() %>%\n  transmute(\n    tract_name,\n    GEOID,\n    child_pop,\n    pct_covered = round(pct_covered, 3),\n    children_in_gap = round(children_in_gap)\n  ) %>%\n  arrange(desc(children_in_gap)) %>%\n  slice_head(n = 10)\ncat(\"\\n===== TOP 10 GAP TRACTS =====\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===== TOP 10 GAP TRACTS =====\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(top_gap_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                               tract_name       GEOID child_pop\n1  Census Tract 348.02; Philadelphia County; Pennsylvania 42101034802      1523\n2  Census Tract 347.01; Philadelphia County; Pennsylvania 42101034701      1556\n3  Census Tract 363.03; Philadelphia County; Pennsylvania 42101036303      1972\n4     Census Tract 361; Philadelphia County; Pennsylvania 42101036100      1162\n5     Census Tract 373; Philadelphia County; Pennsylvania 42101037300      1344\n6     Census Tract 358; Philadelphia County; Pennsylvania 42101035800      1416\n7  Census Tract 357.02; Philadelphia County; Pennsylvania 42101035702      1036\n8  Census Tract 365.02; Philadelphia County; Pennsylvania 42101036502       933\n9     Census Tract 346; Philadelphia County; Pennsylvania 42101034600       552\n10 Census Tract 337.01; Philadelphia County; Pennsylvania 42101033701      1904\n   pct_covered children_in_gap\n1        0.305            1058\n2        0.509             764\n3        0.657             676\n4        0.457             631\n5        0.534             626\n6        0.580             595\n7        0.447             572\n8        0.447             516\n9        0.092             501\n10       0.758             460\n```\n\n\n:::\n\n```{.r .cell-code}\n# Maps\n# Coverage percent choropleth\nggplot() +\n  geom_sf(data = tracts_cov, aes(fill = pct_covered), color = NA) +\n  geom_sf(data = phila_boundary, fill = NA, color = \"grey40\", linewidth = 0.2) +\n  scale_fill_viridis_c(name = \"Coverage by area\", labels = scales::percent_format(accuracy = 1)) +\n  labs(\n    title = \"School Service Coverage by Tract — Philadelphia\",\n    subtitle = \"0.5 mile buffer around schools; tract coverage by area overlap\",\n    caption = \"Schools: OpenDataPhilly; Children: ACS 2022 (B09001_001); CRS: EPSG 2272\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Zhiyuan_Zhao_assignment2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Children outside service areas (areal-weighted)\nggplot() +\n  geom_sf(data = tracts_cov, aes(fill = children_in_gap), color = NA) +\n  geom_sf(data = phila_boundary, fill = NA, color = \"grey40\", linewidth = 0.2) +\n  scale_fill_viridis_c(name = \"Children outside 0.5 mi\", labels = scales::comma) +\n  labs(\n    title = \"Children Outside 0.5-mile School Service Areas\",\n    subtitle = \"Areal-weighted estimate per tract\",\n    caption = \"ACS 2022 (B09001_001); CRS: EPSG 2272\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Zhiyuan_Zhao_assignment2_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:** - Clear code comments explaining each step - Appropriate CRS transformations - Summary statistics or counts - At least one map showing your findings - Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nPhiladelphia tracts show high access overall: 95.1% of children live within 0.5 miles of a school; 4.8% are outside service areas. Coverage by tract: 322 well covered (≥90%), 57 partially covered (50–90%), 29 gaps (<50%), totaling 293,209, 41,085, and 8,291 children respectively. The largest unmet-need tracts by children outside service areas include Census Tracts 348.02, 347.01, 363.03, 361, 373, 358, 357.02, 365.02, 346, 337.01. Maps confirm a small number of edge tracts drive most gaps; prioritizing these for new sites or access improvements would yield the highest impact.\n\n## Finally - A few comments about your incorporation of feedback!\n\nI used include=FALSE to hide my API, removed the empty [], deleted some overly long instructions and improved the variable names to make the code easier to read.\n\n------------------------------------------------------------------------\n\n",
    "supporting": [
      "Zhiyuan_Zhao_assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}